- client-sdk/ts-web/core/README.md
- client-sdk/ts-web/core/src/beacon.ts
- client-sdk/ts-web/core/src/common.ts
- client-sdk/ts-web/core/src/consensus.ts
- client-sdk/ts-web/core/src/control.ts
- client-sdk/ts-web/core/src/epochtime_mock.ts
- client-sdk/ts-web/core/src/index.ts
- client-sdk/ts-web/core/src/keymanager.ts
- client-sdk/ts-web/core/src/registry.ts
- client-sdk/ts-web/core/src/roothash.ts
- client-sdk/ts-web/core/src/runtime.ts
- client-sdk/ts-web/core/src/scheduler.ts
- client-sdk/ts-web/core/src/signature.ts
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/core/src/storage.ts
- client-sdk/ts-web/core/src/types.ts
- client-sdk/ts-web/core/src/upgrade.ts
- client-sdk/ts-web/core/src/worker.ts
transferring docstrings from go codebase
also some corrections and minor additions that I noticed when I went through to do that
> ts-web/core: transfer docstrings

- client-sdk/ts-web/core/playground/sample-envoy.yaml
- client-sdk/ts-web/core/src/address.ts
- client-sdk/ts-web/core/src/beacon.ts
- client-sdk/ts-web/core/src/common.ts
- client-sdk/ts-web/core/src/consensus.ts
- client-sdk/ts-web/core/src/control.ts
- client-sdk/ts-web/core/src/epochtime_mock.ts
- client-sdk/ts-web/core/src/governance.ts
- client-sdk/ts-web/core/src/index.ts
- client-sdk/ts-web/core/src/registry.ts
- client-sdk/ts-web/core/src/roothash.ts
- client-sdk/ts-web/core/src/runtime.ts
- client-sdk/ts-web/core/src/signature.ts
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/core/src/storage.ts
- client-sdk/ts-web/core/src/types.ts
- client-sdk/ts-web/core/src/upgrade.ts
- client-sdk/ts-web/package-lock.json
fixes #9 
This brings ts-web/core to oasis-core rev e000dfaf06a1e3a58f1eb3ca99c24922fac7aea5
> pull in changes from oasis-core master

- .github/workflows/ci-lint.yml
- .github/workflows/ci-test.yaml
- Cargo.lock
- README.md
- runtime-sdk/Cargo.toml
- runtime-sdk/src/context.rs
- runtime-sdk/src/crypto/signature/ed25519.rs
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/accounts/test.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/runtime.rs
- runtime-sdk/src/testing/keys.rs
- runtime-sdk/src/testing/mock.rs
- runtime-sdk/src/testing/mod.rs
- runtime-sdk/src/types/address.rs
- runtime-sdk/src/types/token.rs
- runtime-sdk/src/types/transaction.rs
> runtime-sdk: Add fee payment and disbursement

- .github/workflows/ci-lint.yml
- client-sdk/ts-web/.prettierrc.js
- client-sdk/ts-web/core/src/address.ts
- client-sdk/ts-web/core/src/common.ts
- client-sdk/ts-web/core/src/consensus.ts
- client-sdk/ts-web/core/src/hash.ts
- client-sdk/ts-web/core/src/index.ts
- client-sdk/ts-web/core/src/misc.ts
- client-sdk/ts-web/core/src/roothash.ts
- client-sdk/ts-web/core/src/signature.ts
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/core/src/storage.ts
- client-sdk/ts-web/core/src/types.ts
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/package.json
- client-sdk/ts-web/rt/src/accounts.ts
- client-sdk/ts-web/rt/src/address.ts
- client-sdk/ts-web/rt/src/signature_secp256k1.ts
- client-sdk/ts-web/rt/src/transaction.ts
- client-sdk/ts-web/rt/src/types.ts
- client-sdk/ts-web/rt/src/wrapper.ts
- client-sdk/ts-web/signer-ledger/src/index.ts
The prettierrc is intended to codify the pre-existing style
> Lint ts-web client using prettier

- .github/workflows/ci-test.yaml
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/package.json
- run the typescript compile
- try compiling the playground scripts
> ts-web: typecheck everything in CI

- runtime-sdk/src/context.rs
max messages allowed, inclusive
> context: allow exactly up to max messages

- client-sdk/go/go.mod
- client-sdk/go/go.sum
- client-sdk/ts-web/core/playground/consts.sh
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/core/src/types.ts
this brings us up to https://github.com/oasisprotocol/oasis-core/commit/d186644faee8ab99cc1e94df4bdcf04a92873e00
on top of #40
> ts-web/core: pull in changes from oasis-core master

- .github/workflows/ci-test.yaml
- client-sdk/ts-web/rt/cypress/integration/playground.spec.js
- client-sdk/ts-web/rt/playground/build-runtime.sh
- client-sdk/ts-web/rt/playground/consts.sh
- client-sdk/ts-web/rt/playground/download-artifacts.sh
- client-sdk/ts-web/rt/playground/sample-envoy.yaml
- client-sdk/ts-web/rt/playground/sample-run-envoy.sh
- client-sdk/ts-web/rt/playground/sample-run-network.sh
- client-sdk/ts-web/rt/playground/src/index.js
> ts-web/rt tests with keyvalue runtime

- .github/workflows/ci-test.yaml
- tests/e2e/go.mod
- tests/e2e/simplekvtest.go
- tests/run-e2e.sh
> CI: Run e2e test harness

- runtime-sdk/Cargo.toml
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/storage/mkvs.rs
- runtime-sdk/src/storage/mod.rs
- runtime-sdk/src/storage/overlay.rs
- runtime-sdk/src/storage/prefix.rs
- runtime-sdk/src/storage/typed.rs
- runtime-sdk/src/types/address.rs
- runtime-sdk/src/types/token.rs
resolves #76 
this PR is an RFC. I won't be sad if it's rejected.
> Remove StorageKey traits

- client-sdk/ts-web/core/playground/sample-envoy.yaml
- client-sdk/ts-web/core/playground/src/index.js
fixes #48
we're so bad about Go's empty values :laughing:
> ts-web/core: exercise new convenience calls

- README.md
- client-sdk/ts-web/core/docs/getting-started.md
> docs updates

- runtime-sdk/src/error.rs
- runtime-sdk/src/event.rs
- runtime-sdk/src/module.rs
creating dummy events, errors, and parameters gets tedious
> impl module associated type traits for sane default types

- tests/e2e/scenarios.go
- tests/e2e/simplekvtest.go
- tests/runtimes/simple-keyvalue/src/keyvalue.rs
> e2e: Add test for events

- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
for use in https://github.com/oasisprotocol/oasis-bridge/pull/40
> ts-web/rt: v0.2.0-alpha1

- Cargo.lock
- client-sdk/go/crypto/signature/secp256k1/secp256k1.go
- client-sdk/go/crypto/signature/secp256k1/secp256k1_test.go
- client-sdk/go/crypto/signature/secp256k1/signer.go
- client-sdk/go/go.mod
- client-sdk/go/go.sum
- client-sdk/go/testing/testing.go
- client-sdk/go/testing/testing_test.go
- runtime-sdk/Cargo.toml
- runtime-sdk/src/crypto/signature/secp256k1.rs
- runtime-sdk/src/testing/keys.rs
- tests/e2e/scenarios.go
- tests/e2e/simplekvtest.go
- tests/run-e2e.sh
- tests/runtimes/simple-keyvalue/src/lib.rs
> client-sdk/go/crypto: Implement secp256k1 signer

- client-sdk/ts-web/signer-ledger/docs/changelog.md
- client-sdk/ts-web/signer-ledger/src/index.ts
> ts-web/signer-ledger: add fromTransport

- runtime-sdk/src/context.rs
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/112
> runtime-sdk: test max messages in context

- .github/workflows/ci-test.yaml
- Cargo.lock
- client-sdk/go/go.mod
- client-sdk/go/go.sum
- client-sdk/go/modules/consensusaccounts/consensus_accounts.go
- client-sdk/go/modules/consensusaccounts/types.go
- client-sdk/ts-web/rt/cypress/integration/playground.spec.js
- client-sdk/ts-web/rt/playground/README.md
- client-sdk/ts-web/rt/playground/build-runtime.sh
- client-sdk/ts-web/rt/playground/consts.sh
- client-sdk/ts-web/rt/playground/public/consensus.html
- client-sdk/ts-web/rt/playground/sample-run-network.sh
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/playground/staking.json
- client-sdk/ts-web/rt/playground/webpack.config.js
- client-sdk/ts-web/rt/src/consensus_accounts.ts
- client-sdk/ts-web/rt/src/index.ts
- client-sdk/ts-web/rt/src/types.ts
- runtime-sdk/Cargo.toml
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/consensus_accounts/types.rs
- tests/consts.sh
- tests/e2e/go.mod
- tests/e2e/go.sum
- tests/e2e/simple_consensus.go
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/113
TODO:
> consensus sdk clients

- runtime-sdk/src/dispatcher.rs
> runtime-sdk: Do not vote for obviously malformed transactions

- .github/dependabot.yml
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/79
Hopefully the spam wont be to bad :grin:
> ops: setup dependabot

- client-sdk/go/modules/core/core.go
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- runtime-sdk/src/types/transaction.rs
- tests/e2e/simplekvtest.go
- tests/runtimes/simple-consensus/src/lib.rs
- tests/runtimes/simple-keyvalue/src/lib.rs
- tests/runtimes/simple-keyvalue/src/test.rs
> combined static dispatch for methods and full dispatcher in methods

- client-sdk/ts-web/core/docs/getting-started.md
from https://github.com/oasisprotocol/oasis-sdk/pull/170#discussion_r644510609
> ts-web/core: docs correction

- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/package.json
we can use webpack 5 for signer-ledger with ProvidePlugin
includes #180
> ts-web: sync webpack version

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/src/types.ts
new staking debonding_start event
> ts-web/core: update to oasis-core v21.2.1

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/docs/changelog.md
- client-sdk/ts-web/signer-ledger/package.json
it's been a good while. we'd like to get these changes out and bring the adjacently downstream bridge module going with these new features
> ts-web: new releases

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/package-lock.json
I had incorrectly moved it to dev dependency
> ts-web/core: correct bech32 dependency

- runtime-sdk/src/context.rs
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/accounts/test.rs
- runtime-sdk/src/modules/consensus/mod.rs
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- runtime-sdk/src/modules/rewards/mod.rs
- runtime-sdk/src/runtime.rs
- runtime-sdk/src/testing/mock.rs
- runtime-sdk/src/types/address.rs
- tests/e2e/runtime.go
- tests/e2e/txgen/txgen.go
- tests/runtimes/simple-keyvalue/src/keyvalue.rs
> runtime-sdk: Add invariant checker

- .gitbook.yaml
- .github/workflows/ci-lint.yml
- .markdownlint.yml
- docs/guide/getting-started.md
- docs/guide/minimal-runtime.md
- docs/guide/modules.md
- docs/index.md
- docs/toc.md
> docs: Initial structure

- .github/workflows/ci-docs.yaml
- docs/toc.md
> ci: Add Rust documentation builder action

- .github/workflows/ci-test.yaml
- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/src/consensus.ts
- client-sdk/ts-web/core/src/signature.ts
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/ext-utils/sample-ext/src/index.js
- client-sdk/ts-web/ext-utils/sample-page/src/index.js
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/src/accounts.ts
- client-sdk/ts-web/rt/src/consensus_accounts.ts
- client-sdk/ts-web/rt/src/event.ts
- client-sdk/ts-web/rt/src/transaction.ts
this will be useful for the extension side when it gets a ContextSigner.sign request
> ts-web: parsing a signature request

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/ext-utils/docs/changelog.md
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
this is for our developer partners so they can get our new browser extension signer interface and transaction parsing from npm
> ts-web: alpha releases for core, rt, and ext-utils

- runtime-sdk/src/modules/core/types.rs
- runtime-sdk/src/runtime.rs
- tests/runtimes/simple-consensus/src/lib.rs
- tests/runtimes/simple-keyvalue/src/lib.rs
> runtime-sdk: Add state migration helpers

- .github/workflows/ci-test.yaml
- client-sdk/ts-web/core/docs/getting-started.md
> ci: change envoy install

- .github/workflows/ci-lint.yml
- .markdownlint.yml
> disable markdown code block line length limit

- client-sdk/ts-web/ext-utils/docs/changelog.md
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
make a release after we finish #285
> ts-web/ext-utils: v0.1.0-alpha2

- tests/benchmark/run-benchmarks.sh
> benchmarks: bump concurrency

- client-sdk/ts-web/ext-utils/sample-ext/src/index.js
fixes #279 
this implements similar behavior by using window.open()
the window opener is an extension, so the popup blocker normally won't mess with it.
unfortunate downside: there's no longer anything to display that the popup comes from the extension origin. but other origins impersonating these popups won't be able to sign, so it's not that bad
> ts-web/ext-utils: replace alert/confirm

- .github/actions/hash-rust/action.yml
- .github/workflows/ci-reproducibility.yml
- docs/guide/reproducing.md
- docs/toc.md
> ci: Add check for build reproducibility

- client-sdk/ts-web/ext-utils/docs/changelog.md
- client-sdk/ts-web/ext-utils/package.json
> ts-web/ext-utils: v0.1.0-alpha3

- .github/workflows/ci-lint.yml
- .github/workflows/ci-test.yaml
to follow #342
looks like they've added support for exotic repo layouts like ours
> ci: enable npm packages cache 

- client-sdk/go/modules/accounts/accounts.go
- client-sdk/go/modules/accounts/types.go
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/src/accounts.ts
- client-sdk/ts-web/rt/src/types.ts
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/accounts/test.rs
- runtime-sdk/src/modules/accounts/types.rs
- tests/e2e/simple_consensus.go
- tests/e2e/simplekvtest.go
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/239
TODO:
> runtime-sdk/accounts: add accounts.Addresses query to list all addresses

- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/playground/src/index.js
- codecov.yml
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/accounts/test.rs
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/consensus_accounts/test.rs
- runtime-sdk/src/runtime.rs
- runtime-sdk/src/storage/mkvs.rs
- runtime-sdk/src/storage/mod.rs
- tests/benchmark/cmd/fixture.go
- tests/runtimes/benchmarking/src/runtime/mod.rs
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/278
This is ready for some reviews, before i finish by implementing prefetch in other modules.
TODO:
> runtime-sdk: add prefetching support

- .github/workflows/ci-docs.yaml
- Cargo.lock
- Cargo.toml
- contract-sdk/storage/Cargo.toml
- contract-sdk/storage/src/cell.rs
- contract-sdk/storage/src/lib.rs
- contract-sdk/storage/src/map.rs
- tests/contracts/hello/Cargo.lock
- tests/contracts/hello/Cargo.toml
- tests/contracts/hello/src/lib.rs
> contract-sdk: Add high-level storage abstraction

- Cargo.lock
- client-sdk/go/modules/evm/evm.go
- client-sdk/go/modules/evm/types.go
- runtime-sdk/modules/evm/Cargo.toml
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/types.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/accounts/test.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- tests/e2e/scenarios.go
- tests/e2e/simpleevmtest.go
- tests/e2e/txgen/generators.go
- tests/e2e/txgen/txgen.go
- tests/runtimes/benchmarking/src/lib.rs
- tests/runtimes/simple-consensus/src/lib.rs
- tests/runtimes/simple-evm/src/lib.rs
- tests/runtimes/simple-keyvalue/src/lib.rs
- tests/runtimes/simple-keyvalue/src/test.rs
> runtime-sdk/modules/evm: Add withdraw/deposit

- Cargo.lock
- runtime-sdk/modules/evm/Cargo.toml
- runtime-sdk/modules/evm/src/evm_backend.rs
- runtime-sdk/modules/evm/src/lib.rs
> runtime-sdk/modules/evm: Use HashedStore for storage

- client-sdk/go/modules/evm/evm.go
- client-sdk/go/modules/evm/types.go
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/test.rs
- runtime-sdk/modules/evm/src/types.rs
- runtime-sdk/src/modules/accounts/mod.rs
- tests/e2e/simpleevmtest.go
> runtime-sdk/modules/evm: Add more tests and fixes

- tests/check-core-versions.sh
modules that only have one dependency get rewritten without the parentheses, so we can't look for a verbatim line match
I guess we'll start writing our own parser then :roll_eyes:
> tests: fix syntax difference with single-dependency modules

- Cargo.lock
- runtime-sdk/modules/evm/Cargo.toml
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/precompile.rs
Add support for ethereum precompiled contract.
> runtime-sdk/modules/evm: support precompiled contracts for evm

- client-sdk/go/modules/core/core.go
- client-sdk/go/modules/rewards/rewards.go
- client-sdk/ts-web/rt/playground/sample-run-network.sh
- runtime-sdk/modules/contracts/src/lib.rs
- runtime-sdk/src/context.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/testing/mock.rs
- tests/e2e/runtime.go
> Various minor cleanups

- runtime-sdk/modules/evm/src/lib.rs
suggested in a comment in #452
> modules/evm: allow derive caller from any address spec

- Cargo.lock
- runtime-sdk/modules/evm/Cargo.toml
- runtime-sdk/modules/evm/src/derive_caller.rs
> modules/evm: switch to sha3 crate for keccak

- runtime-sdk/modules/evm/src/precompile.rs
To make it consistent with with the Ethereum transaction signature verification (added in https://github.com/oasisprotocol/oasis-sdk/pull/452)
> evm/precompile: reject high s in erecover precompile

- client-sdk/ts-web/core/cypress/integration/playground.spec.js
- client-sdk/ts-web/core/playground/sample-envoy.yaml
- client-sdk/ts-web/rt/cypress/integration/playground.spec.js
- client-sdk/ts-web/rt/playground/sample-envoy.yaml
a few misc things for upcoming work on #327
> grpc error details supporting changes

- client-sdk/ts-web/core/.gitignore
- client-sdk/ts-web/core/compile-proto.sh
- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/core/proto/grpc/status/status.proto
- client-sdk/ts-web/core/src/client.ts
- client-sdk/ts-web/package-lock.json
this other library has a smaller bundle size impact
also typescript declarations :heart_eyes:
> grpc error details, protobufjs variant

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/package.json
a release to get our error improvements out to developers
> ts-web/core: version 0.1.0-alpha6

- client-sdk/go/client/client.go
- client-sdk/go/modules/accounts/accounts.go
- client-sdk/go/modules/accounts/types.go
- client-sdk/go/modules/contracts/contracts.go
- client-sdk/go/modules/contracts/oas20/oas20.go
- client-sdk/go/modules/contracts/types.go
- client-sdk/go/types/event.go
- contract-sdk/specs/oas20/README.md
- contract-sdk/specs/oas20/types/src/helpers.rs
- contract-sdk/specs/oas20/types/src/lib.rs
- tests/e2e/contracts.go
- tests/e2e/simplekvtest.go
- adds support for querying sdk events to the go client-sdk
- adds support for querying contract events
> client-sdk/go: module events

- runtime-sdk/src/modules/accounts/mod.rs
huh, we even had the event types all laid out
we wanted this to improve our tests for deposit/withdraw, in #544
> modules/accounts: emit events on mint and burn

- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
we want to get queryDenominationInfo out to our developers
> ts-web/rt: v0.2.0-alpha6

- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/src/signature_secp256k1.ts
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/consensus_accounts/test.rs
along with some fixes elsewhere to make this work
and a release of client-rt
> ts-web/rt: playground make deposit/withdraw cross-account

- client-sdk/go/modules/accounts/types.go
- client-sdk/go/modules/consensusaccounts/consensus_accounts.go
- client-sdk/go/modules/consensusaccounts/types.go
- client-sdk/ts-web/rt/src/consensus_accounts.ts
- client-sdk/ts-web/rt/src/types.ts
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/consensus_accounts/test.rs
- runtime-sdk/src/modules/consensus_accounts/types.rs
- tests/e2e/simple_consensus.go
> modules/consensus_accounts: Add Deposit/Withdraw events

- client-sdk/go/modules/consensusaccounts/types.go
- client-sdk/ts-web/core/src/address.ts
- client-sdk/ts-web/ext-utils/src/ext.ts
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/playground/src/index.js
- client-sdk/ts-web/rt/src/consensus_accounts.ts
- client-sdk/ts-web/rt/src/types.ts
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/consensus_accounts/test.rs
- runtime-sdk/src/modules/consensus_accounts/types.rs
- tests/e2e/simple_consensus.go
with some additional changes to use these events in the consensus playground
> modules/consensus_accounts: substitute nonce for id in events

- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/test.rs
Configure `gasometer` to use `estimate` mode when estimating transaction gas costs.
> evm/config: use estimate in simulation

- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
we'd like to have our devs try out the new deposit/withdraw events
> ts-web/rt: v0.2.0-alpha8

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/src/client.ts
cc https://github.com/oasisprotocol/oasis-wallet-web/pull/498
> ts-web/core: grpc-web error wrapping

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/package.json
with the new grpc client error wrapping
> ts-web/core: 0.1.0-alpha8

- runtime-sdk/modules/contracts/src/abi/oasis/test.rs
- runtime-sdk/modules/contracts/src/lib.rs
- runtime-sdk/modules/contracts/src/results.rs
- runtime-sdk/modules/contracts/src/test.rs
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/test.rs
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/consensus/mod.rs
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- runtime-sdk/src/runtime.rs
- runtime-sdk/src/testing/mock.rs
- tests/runtimes/benchmarking/src/lib.rs
- tests/runtimes/simple-consensus/src/lib.rs
- tests/runtimes/simple-evm/src/lib.rs
- tests/runtimes/simple-keyvalue/src/keyvalue.rs
- tests/runtimes/simple-keyvalue/src/lib.rs
- tests/runtimes/simple-keyvalue/src/test.rs
Actual configuration values will be added in a separate PR, this one has no other functional changes.
> runtime-sdk: Support configuration for core module

- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
Based on #743.
Adds support for local minimum gas price overrides.
> runtime-sdk: Support local minimum gas price overrides

- Cargo.lock
- contract-sdk-macros/Cargo.toml
- contract-sdk-macros/src/test_utils.rs
- runtime-sdk-macros/Cargo.toml
- runtime-sdk-macros/src/generators.rs
- runtime-sdk-macros/src/lib.rs
- runtime-sdk-macros/src/method_handler_derive.rs
- runtime-sdk-macros/src/test_utils.rs
- runtime-sdk/modules/contracts/src/lib.rs
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/consensus/mod.rs
- runtime-sdk/src/modules/consensus_accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
Resolves https://github.com/oasisprotocol/oasis-sdk/issues/24
Prerequisite for https://github.com/oasisprotocol/oasis-sdk/issues/652 (as it will enable introspection)
> proc_macro for deriving the `MethodHandler` trait

- client-sdk/ts-web/rt/src/contracts.ts
- client-sdk/ts-web/rt/src/index.ts
- client-sdk/ts-web/rt/src/types.ts
writing up the typescript bindings. need to port a lot of types :dizzy_face:
> ts-web/rt: add contracts module

- client-sdk/ts-web/ext-utils/sample-page/src/index.js
why didn't I do this when I added it to misc :facepalm:
> ts-web/ext-utils: switch to oasis.misc.toBase64 in sample-page

- client-sdk/go/config/default.go
Update testnet chain context for version 2022-03-03
> client-sdk/go: update testnet chain context

- runtime-sdk/src/dispatcher.rs
> [BACKPORT/0.2.x] runtime-sdk: Re-check transactions before scheduling

- runtime-sdk/src/context.rs
Currently, if a runtime's local config has a value that is syntactically valid but of an incorrect type (e.g. `0x132` instead of `"0x123"`), the config entry will be silently ignored.
I was thinking this would be nice to have as I was walking through the code ... Then chose not to get sidetracked ... Then a day later, got bitten by hidden bug caused by a mistyped local-config value :)
I think panicking, rather than warning, is the right thing to do from a UX perspective. It's unfortunate that we panic on the first use of each config value, rather than at initialization time, but I don't think we can do better as long as `LocalConfig` remains schema-less and module initialization is static.
*Testing*: Intentionally changed the type of a local config entry used by the core module, ran e2e …
> runtime-sdk: Panic on malformed local config

- client-sdk/ts-web/rt/playground/sample-run-network.sh
- client-sdk/ts-web/rt/src/core.ts
- runtime-sdk-macros/src/lib.rs
- runtime-sdk-macros/src/method_handler_derive.rs
- runtime-sdk/modules/contracts/src/lib.rs
- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/src/context.rs
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- runtime-sdk/src/testing/mock.rs
- runtime-sdk/src/testing/mod.rs
- tests/benchmark/cmd/fixture.go
- tests/e2e/runtime.go
> Configurable queries

- cli/cmd/accounts.go
- cli/cmd/inspect/inspect.go
- cli/cmd/inspect/registry.go
- cli/cmd/inspect/runtime_stats.go
> More CLI commands/improvements

- cli/cmd/accounts.go
- cli/cmd/common/transaction.go
- cli/cmd/contracts.go
- client-sdk/go/callformat/callformat.go
- client-sdk/go/client/callformat.go
- client-sdk/go/client/transaction.go
- client-sdk/go/modules/core/core.go
- client-sdk/go/modules/core/types.go
- client-sdk/go/types/transaction.go
- runtime-sdk/modules/contracts/src/results.rs
- runtime-sdk/src/dispatcher.rs
- runtime-sdk/src/module.rs
- runtime-sdk/src/modules/core/mod.rs
Also fixes an issue with call format decoding order.
> cli: Add support for encrypted call format

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/playground/jsconfig.json
- client-sdk/ts-web/core/playground/src/index.js
- client-sdk/ts-web/core/src/client.ts
- client-sdk/ts-web/core/src/consensus.ts
- client-sdk/ts-web/core/src/hdkey.ts
- client-sdk/ts-web/core/src/misc.ts
- client-sdk/ts-web/core/src/signature.ts
- client-sdk/ts-web/core/test/hdkey.test.ts
- client-sdk/ts-web/core/tsconfig.json
- client-sdk/ts-web/ext-utils/docs/changelog.md
- client-sdk/ts-web/ext-utils/sample-ext/jsconfig.json
- client-sdk/ts-web/ext-utils/sample-ext/src/index.js
- client-sdk/ts-web/ext-utils/sample-page/jsconfig.json
- client-sdk/ts-web/ext-utils/sample-page/src/index.js
- client-sdk/ts-web/ext-utils/src/connection.ts
- client-sdk/ts-web/ext-utils/src/signature.ts
- client-sdk/ts-web/ext-utils/tsconfig.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/playground/jsconfig.json
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/src/address.ts
- client-sdk/ts-web/rt/src/event.ts
- client-sdk/ts-web/rt/src/transaction.ts
- client-sdk/ts-web/rt/src/types.ts
- client-sdk/ts-web/rt/src/wrapper.ts
- client-sdk/ts-web/rt/tsconfig.json
- client-sdk/ts-web/signer-ledger/playground/jsconfig.json
- client-sdk/ts-web/signer-ledger/tsconfig.json
checking what complaints come up in strict mode
reviewers: ignore whitespace due to some indentation changes
> ts-web: typescript strict mode

- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/signer-ledger/docs/changelog.md
- client-sdk/ts-web/signer-ledger/package.json
the version numbering is updated, see #948
> ts-web/signer-ledger: v0.1.1-alpha.1

- runtime-sdk/modules/evm/src/test.rs
- runtime-sdk/src/context.rs
re: https://github.com/oasisprotocol/oasis-sdk/pull/926#issuecomment-1141976867
> runtime-sdk: add some tests

- cli/cmd/common/transaction.go
- client-sdk/go/modules/core/core.go
- client-sdk/go/modules/core/types.go
- client-sdk/ts-web/rt/src/types.ts
- runtime-sdk/src/context.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
- runtime-sdk/src/modules/core/types.rs
- tests/e2e/simpleevmtest.go
- tests/e2e/simplekvtest.go
- tests/e2e/txgen/txgen.go
Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/965
> runtime-sdk: optional error propagation in core.EstimateGas

- runtime-sdk/modules/evm/README.md
- runtime-sdk/modules/evm/src/backend.rs
- runtime-sdk/modules/evm/src/precompile.rs
- runtime-sdk/src/context.rs
- runtime-sdk/src/modules/accounts/mod.rs
- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
* runtime-sdk: Implement `Context` for `RefMut<'_, Context>`
* evm: Improve compatibility and document more differences
> evm: Improve compatibility and document more differences

- Cargo.lock
- contract-sdk-macros/Cargo.toml
- contract-sdk-macros/src/error_derive.rs
- contract-sdk-macros/src/event_derive.rs
- contract-sdk/specs/access/oas173/Cargo.lock
- contract-sdk/specs/token/oas20/Cargo.lock
- runtime-sdk-macros/Cargo.toml
- runtime-sdk-macros/src/error_derive.rs
- runtime-sdk-macros/src/event_derive.rs
- tests/contracts/hello/Cargo.lock
See changelog: https://github.com/TedDriggs/darling/releases
> runtime-sdk: bump darling from 0.13.4 to 0.14.1

- docs/contract/hello-world.md
Preview: https://github.com/oasisprotocol/oasis-sdk/blob/matevz/docs/cipher-contracts-cargo-test/docs/contract/hello-world.md#testing
> docs: Add cargo test for smart contracts

- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
> ts-web/rt: v0.2.1-alpha.2

- client-sdk/ts-web/ext-utils/README.md
- client-sdk/ts-web/ext-utils/docs/getting-started.md
Part of oasisprotocol/docs#223
> docs: Rename DApp -> dApp for consistency

- client-sdk/ts-web/README.md
- client-sdk/ts-web/core/README.md
- client-sdk/ts-web/core/docs/getting-started.md
> ts-web: docs additions

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/src/client.ts
- client-sdk/ts-web/core/src/types.ts
- examples/client-sdk/go/minimal-runtime-client/go.mod
- tests/check-core-versions.sh
> ts-web/core: update types + client

- .github/workflows/ci-test.yaml
- client-sdk/ts-web/core/reflect-go/main.go
the new functionality used in #1210
> ts-web/core: reflect client methods

- Cargo.lock
- contract-sdk/specs/access/oas173/Cargo.lock
- contract-sdk/specs/token/oas20/Cargo.lock
- runtime-sdk/Cargo.toml
- tests/contracts/bench/Cargo.lock
- tests/contracts/hello/Cargo.lock
follow-up to #1037 post-merge comments
> runtime-sdk: remove schnorrkel cargo features

- client-sdk/go/types/transaction.go
- client-sdk/go/types/transaction_test.go
Before:
```
$ oasis tx show testtx2.json --network mainnet
Hash: 3013be1ba6e1ef17921382f01b53f519174b2f35753d1fc37ad11bfc382f51f5
Signer(s):
1. NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE=
(signature: mxOARaaRkHrHiUObGO2KbUXZhmbIS2h3hsRM+3Y/DzvMtbVdwcZm2EZ7oP7dR5XHKkrQnjMwZnkT0mdZUsLIBw==)
[INVALID SIGNATURE]
Content:
Format: plain
Method: accounts.Transfer
Body:
To: test:bob (oasis1qrydpazemvuwtnp3efm7vmfvg3tde044qg6cxwzx)
Amount: 1.0 ROSE
Authorized signer(s):
1. NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE= (ed25519)
Nonce: 1
Fee:
Amount: 0.0 ROSE
Gas limit: 1
(gas price: 0.0 ROSE per gas unit)
Network:  mainnet
ParaTime: emerald
```
After:
```
$ oasis tx show testtx2.json  --network mainnet
Hash: 3013be1ba6e1ef17921382f01b53f519174b2f35753d1fc37ad11bfc382f51f5
Signer(s):
1. …
```
> client-sdk/go: Indent numbered list for PrettyPrint

- client-sdk/ts-web/package-lock.json
holding this here so dependabot can still rebase automatically
> client/ts-web: bump @types/node

- runtime-sdk/src/modules/core/mod.rs
- runtime-sdk/src/modules/core/test.rs
Testing has shown that having this enabled globally leads to bad estimates even for methods where regular estimation should work just fine. This makes the extra gas estimations per-method.
> runtime-sdk: Make extra gas estimation per method

- docs/contract/hello-world.md
- docs/contract/prerequisites.md
- docs/runtime/minimal-runtime.md
- docs/runtime/modules.md
- docs/runtime/prerequisites.md
See https://github.com/oasisprotocol/docs/pull/525
> docs: Consistently use part/chapter/section terms

- LICENSE-docs
- README.md
See https://github.com/oasisprotocol/docs/pull/440
> docs: License the documentation under CC BY 4.0

- runtime-sdk/modules/evm/src/lib.rs
- runtime-sdk/modules/evm/src/raw_tx.rs
- tests/e2e/evmtest.go
- tests/e2e/scenarios.go
> runtime-sdk/modules/evm: Fix EIP-1559 gas price calculation

- .github/dependabot.yml
y'all cool kids are doing it with go and rust
> ts-web: dependabot group dev dependency bumps

- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/core/src/hash.ts
- client-sdk/ts-web/core/src/hdkey.ts
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/rt/playground/src/consensus.js
- client-sdk/ts-web/rt/playground/src/index.js
- client-sdk/ts-web/rt/src/address.ts
- client-sdk/ts-web/rt/src/callformat.ts
- client-sdk/ts-web/rt/src/mrae/deoxysii.ts
- client-sdk/ts-web/rt/src/signature_secp256k1.ts
- client-sdk/ts-web/rt/test/callformat.test.ts
> ts-web: trying out other crypto libraries

- client-sdk/go/modules/rofl/app_id.go
- client-sdk/go/modules/rofl/app_id_test.go
- client-sdk/go/modules/rofl/types.go
- runtime-sdk/src/modules/rofl/app_id.rs
- runtime-sdk/src/modules/rofl/mod.rs
- runtime-sdk/src/modules/rofl/test.rs
- runtime-sdk/src/modules/rofl/types.rs
> runtime-sdk/modules/rofl: Add a deterministic ID generation scheme

- Cargo.lock
- rofl-appd/Cargo.toml
- rofl-appd/src/lib.rs
- rofl-appd/src/routes/mod.rs
- rofl-appd/src/routes/tx.rs
- rofl-appd/src/state.rs
- rofl-containers/Cargo.toml
- runtime-sdk/src/modules/rofl/app/client.rs
> rofl-appd: Optionally add the transaction endpoints

- Cargo.lock
- contract-sdk/specs/access/oas173/Cargo.lock
- contract-sdk/specs/token/oas20/Cargo.lock
- examples/runtime-sdk/rofl-oracle-tdx/Cargo.lock
- examples/runtime-sdk/rofl-oracle/Cargo.lock
- runtime-sdk/Cargo.toml
- runtime-sdk/src/modules/rofl/app/client.rs
- runtime-sdk/src/modules/rofl/mod.rs
- runtime-sdk/src/modules/rofl/test.rs
- runtime-sdk/src/modules/rofl/types.rs
- tests/contracts/bench/Cargo.lock
- tests/contracts/hello/Cargo.lock
> runtime-sdk/modules/rofl: Add key scope in rofl.DeriveKey

- docs/rofl/app.mdx
> docs: Document App ID derivation

- Cargo.lock
- rofl-containers/Cargo.toml
- rofl-containers/src/containers.rs
> rofl-containers: Add --no-build when bringing up containers

- docs/rofl/app.mdx
Followup to https://github.com/oasisprotocol/docs/pull/1165
> docs: Fix 10,000 -> 100 TEST for rofl create command

- Cargo.lock
- Cargo.toml
- runtime-sdk/modules/evm/src/test.rs
- runtime-sdk/modules/rofl-market/Cargo.toml
- runtime-sdk/modules/rofl-market/src/config.rs
- runtime-sdk/modules/rofl-market/src/error.rs
- runtime-sdk/modules/rofl-market/src/event.rs
- runtime-sdk/modules/rofl-market/src/lib.rs
- runtime-sdk/modules/rofl-market/src/payment.rs
- runtime-sdk/modules/rofl-market/src/state.rs
- runtime-sdk/modules/rofl-market/src/test.rs
- runtime-sdk/modules/rofl-market/src/types.rs
- runtime-sdk/src/context.rs
- runtime-sdk/src/modules/rofl/config.rs
- runtime-sdk/src/modules/rofl/mod.rs
- runtime-sdk/src/modules/rofl/state.rs
- runtime-sdk/src/modules/rofl/test.rs
- runtime-sdk/src/types/address.rs
- runtime-sdk/src/types/token.rs
- runtime-sdk/src/types/transaction.rs
> runtime-sdk: Add ROFL compute market

- docs/rofl/prerequisites.md
> Update docker image

- client-sdk/ts-web/core/docs/changelog.md
- client-sdk/ts-web/core/package.json
- client-sdk/ts-web/ext-utils/package.json
- client-sdk/ts-web/package-lock.json
- client-sdk/ts-web/rt/docs/changelog.md
- client-sdk/ts-web/rt/package.json
- client-sdk/ts-web/signer-ledger/package.json
Useful for https://github.com/oasisprotocol/explorer/issues/1955#issuecomment-2870968171
> ts-web: 1.2.0 releases

- rofl-scheduler/rofl.yaml
- rofl-scheduler/src/config.rs
- rofl-scheduler/src/manager.rs
> rofl-scheduler: Add support for transferring instances from nodes

- Cargo.lock
- contract-sdk/specs/access/oas173/Cargo.lock
- contract-sdk/specs/token/oas20/Cargo.lock
- examples/runtime-sdk/rofl-oracle-tdx/Cargo.lock
- examples/runtime-sdk/rofl-oracle/Cargo.lock
- rofl-scheduler/Cargo.toml
- rofl-scheduler/rofl.yaml
- rofl-scheduler/src/config.rs
- rofl-scheduler/src/main.rs
- rofl-scheduler/src/manager.rs
- rofl-scheduler/src/serverd/auth.rs
- rofl-scheduler/src/serverd/error.rs
- rofl-scheduler/src/serverd/mod.rs
- rofl-scheduler/src/serverd/routes.rs
- rofl-scheduler/src/serverd/tls.rs
- runtime-sdk/Cargo.toml
- runtime-sdk/src/modules/rofl/app/mod.rs
- runtime-sdk/src/modules/rofl/app/processor.rs
- runtime-sdk/src/modules/rofl/app/registration.rs
- tests/contracts/bench/Cargo.lock
- tests/contracts/hello/Cargo.lock
> rofl-scheduler: Add API endpoint and route to get logs

- client-sdk/ts-web/rt/src/rofl.ts
- client-sdk/ts-web/rt/src/roflmarket.ts
- client-sdk/ts-web/rt/src/types.ts
Fixes https://github.com/oasisprotocol/oasis-sdk/pull/2243#discussion_r2159457235
> ts-web/rt: cleanup rofl and roflmarket types

- docs/rofl/deployment.mdx
- docs/rofl/quickstart.mdx
Also, add price to offers and add --network parameter to the rofl create command so it's clear where the users can select a different chain.
> docs/rofl: Mention rofl machine logs command

- client-sdk/go/modules/roflmarket/roflmarket.go
- client-sdk/go/modules/roflmarket/types.go
- runtime-sdk/modules/rofl-market/src/config.rs
- runtime-sdk/modules/rofl-market/src/lib.rs
- runtime-sdk/modules/rofl-market/src/test.rs
- runtime-sdk/modules/rofl-market/src/types.rs
> runtime-sdk/modules/rofl-market: Add InstanceChangeAdmin call

- client-sdk/ts-web/core/src/misc.ts
- client-sdk/ts-web/core/src/staking.ts
- client-sdk/ts-web/rt/src/rofl.ts
Fixes https://github.com/oasisprotocol/oasis-sdk/issues/2235
> Validate hex and bech32 input

- client-sdk/ts-web/rt/src/accounts.ts
- client-sdk/ts-web/rt/src/consensus.ts
- client-sdk/ts-web/rt/src/consensus_accounts.ts
- client-sdk/ts-web/rt/src/core.ts
- client-sdk/ts-web/rt/src/evm.ts
- client-sdk/ts-web/rt/src/roflmarket.ts
- client-sdk/ts-web/rt/src/types.ts
Fixes https://github.com/oasisprotocol/oasis-sdk/issues/812 and https://github.com/oasisprotocol/oasis-sdk/issues/2045
> ts-web/rt: add new roflmarket and consensus delegation methods

- rofl-app-core/src/secrets.rs
- rofl-scheduler/src/main.rs
- rofl-scheduler/src/manager.rs
- rofl-scheduler/src/serverd/routes.rs
- rofl-scheduler/src/state.rs
- rofl-scheduler/src/types.rs
- runtime-sdk/modules/rofl-market/src/lib.rs
- runtime-sdk/modules/rofl-market/src/test.rs
> rofl-scheduler: Add support for machine permissions

- docs/rofl/features/secrets.md
resolves https://github.com/oasisprotocol/oasis-sdk/issues/2311
> docs: add link to detailed rofl secrets cli

- rofl-app-core/src/processor.rs
- rofl-proxy/src/http/proxy.rs
- rofl-scheduler/rofl.yaml
> rofl: Various minor tweaks
