LICENSE
client-sdk/ts-web/core/package.json
client-sdk/ts-web/signer-ledger/package.json
runtime-sdk/Cargo.toml

note that the license includes a template at the bottom. don't fill in the fields in that copy of the template, because it's meant to be a template. we have incorrectly done so in our other repos, but don't do it here.

add license

---

client-sdk/ts-web/core/src/common.ts
client-sdk/ts-web/core/src/index.ts
client-sdk/ts-web/core/src/signature.ts
client-sdk/ts-web/core/src/types.ts

this is a draft to see what it would be like.
separate them to have their own prefixes/modules based on the Go codebase's detailed breakdown of the 'common' directory.
I kinda don't like it. but it may be more sustainable if we end up having types with the same name in different 'common' subpackages.
also tries out removing duplicate parts of names, e.g. `CommonNode` -> `NodeNode` -> `Node`.
I kinda don't like that either. seems like we had done this in the Go codebase with things like `consensus.Parameters` instead of `consensus.ConsensusParameters`. we had a lint for it, formerly known as 'stutter' https://github.com/rust-lang/rust-clippy/issues/3521. I personally would have preferred rule simplicity and consistency across packages and longer name (`consensus.ConsensusParameters`) over …

explode common

---

runtime-sdk/src/crypto/signature/mod.rs

This makes it possible to convert signatures outside of serialization
routines.

runtime-sdk: Implement AsRef and From for Signature

---

runtime-sdk/src/context.rs
runtime-sdk/src/crypto/signature/secp256k1.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/lib.rs
runtime-sdk/src/module.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs
runtime-sdk/src/runtime.rs
runtime-sdk/src/storage/overlay.rs
runtime-sdk/src/storage/prefix.rs
runtime-sdk/src/storage/typed.rs
runtime-sdk/src/testing/mock.rs
runtime-sdk/src/types/address.rs
runtime-sdk/src/types/token.rs

This PR denies the following lints
* `unsafe_code` - for obvious reasons
*  `unreachable_pub` - to make sure everything `pub` is intentionally exported
* `rust_2018_idoms` - being current is nice

Deny some rust lints

---

.github/workflows/ci-test.yaml
client-sdk/ts-web/core/playground/sample-envoy.yaml
client-sdk/ts-web/core/playground/src/index.js

depends #54 
This seems to need a little something more, with our test hanging when directed at the client node instead of the validator

ts-web/core: use client node for playground grpc

---

client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/playground/src/index.js
client-sdk/ts-web/core/src/signature.ts
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/playground/src/index.js
client-sdk/ts-web/signer-ledger/playground/src/index.js

Replace the EllipticSigner with NaclSigner
Elliptic is not able to sign using the 64 bytes private key that we will need to use once we support key derivation.
For reference the go package does it right : https://golang.org/pkg/crypto/ed25519/ and allows you to instanciate a keypair from the seed or from the 64 bytes private key.
The whole process is described here : https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/
This is required in order to eventually implement [BIP32-Ed25519](https://github.com/oasisprotocol/oasis-core/pull/3656/)

ts-web/core: revert to tweetnacl

---

.github/workflows/ci-test.yaml
Cargo.lock
Cargo.toml
runtime-sdk-macros/Cargo.toml
runtime-sdk-macros/src/error_derive.rs
runtime-sdk-macros/src/event_derive.rs
runtime-sdk-macros/src/generators.rs
runtime-sdk-macros/src/lib.rs
runtime-sdk-macros/src/test_utils.rs
runtime-sdk-macros/src/version_from_cargo.rs
runtime-sdk/Cargo.toml
runtime-sdk/src/crypto/signature/context.rs
runtime-sdk/src/error.rs
runtime-sdk/src/event.rs
runtime-sdk/src/lib.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/core/mod.rs

this PR adds `version_from_cargo` proc macro because in the one in `oasis_core::runtime::common` uses `parse`, which isn't a `const fn`.

Add version_from_cargo proc macro

---

runtime-sdk-macros/src/error_derive.rs
runtime-sdk/src/error.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/core/mod.rs
tests/runtimes/simple-keyvalue/src/keyvalue.rs

This PR does what it says on the tin. It also removes `sdk::error::Error::msg` because it's a non-standard way of writing `std::error::Error::to_string`.

Apply macros to keyvalue example

---

runtime-sdk-macros/src/error_derive.rs
runtime-sdk-macros/src/event_derive.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/error.rs
runtime-sdk/src/event.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/core/mod.rs
tests/runtimes/simple-keyvalue/src/keyvalue.rs

After attempting to use the macros in the bridge, it became evident that the macros would not easily work with generic `Module` types. I can't really think of a good way to get type information in that wouldn't also degrade developer UX or maintainability of this codebase, so this just makes the module name a const parameter.

runtime-sdk: allow macros to work with generic modules

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/signer-ledger/docs/changelog.md
client-sdk/ts-web/signer-ledger/package.json

We can put a prerelease version on npm. We discussed this internally, and we didn't come up with anything that should block this.
for #7

ts-web: bump versions for alpha release

---

client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/playground/src/index.js
client-sdk/ts-web/rt/src/accounts.ts
client-sdk/ts-web/rt/src/event.ts

I saw a loose TODO in the bridge Go example client that we desired wrappers for working with events. Here's one for the typescript.

ts-web/rt: add typed event visitor

---

client-sdk/ts-web/rt/playground/src/index.js
tests/e2e/runtime.go
tests/e2e/scenarios.go
tests/e2e/simplekvtest.go
tests/runtimes/simple-keyvalue/src/lib.rs

Part of #21.  Adds accounts to the simple-keyvalue runtime and two new end-to-end tests for accounts, also correctly handles account nonces in `kvInsert` and `kvRemove`.

e2e: Add tests for accounts

---

runtime-sdk-macros/src/error_derive.rs
runtime-sdk-macros/src/lib.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/error.rs

SDK errors can now implement the source method which is taken into account when
converting an error into a call result. This makes it possible to nest errors
and make sure that module and code from the most inner error are used.
Seems like it could be useful in #92 and #94 where we started to nest errors.

runtime-sdk: Properly handle error chains

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/src/common.ts
client-sdk/ts-web/core/src/types.ts

all I've seen for API changes is the rename of entity.LatestDescriptorVersion and a rearrangement of ProtocolVersions

ts-web/core: update to oasis-core v21.1.1

---

client-sdk/ts-web/signer-ledger/docs/changelog.md
client-sdk/ts-web/signer-ledger/src/index.ts

@Esya could you check if this fixes the `sign` output?
fixes #106

ts-web/signer-ledger: correct u8FromBuf length

---

runtime-sdk/src/modules/consensus_accounts/mod.rs
tests/runtimes/simple-consensus/src/lib.rs

add parameters and use_gas calls. set to 100 for sample runtime

modules/consensus_accounts: add gas costs for transactions

---

client-sdk/ts-web/signer-ledger/docs/changelog.md
client-sdk/ts-web/signer-ledger/src/index.ts

So no more message string parsing! Unless you're into that kind of thing.

ts-web/signer-ledger: preserve original return code

---

runtime-sdk/src/lib.rs

This PR removes the `const_fn` feature that breaks downstream compilation.
```
error[E0557]: feature has been removed
--> ~/.cargo/git/checkouts/oasis-sdk-c51e681916015383/a26ce5a/runtime-sdk/src/lib.rs:2:12
|
2 | #![feature(const_fn)]
|            ^^^^^^^^ feature has been removed
|
= note: split into finer-grained feature gates
```

runtime-sdk: remove removed const_fn feature

---

runtime-sdk/src/module.rs
tests/runtimes/simple-keyvalue/src/lib.rs
tests/runtimes/simple-keyvalue/src/test.rs

those default implementations are silent but deadly :facepalm:

runtime-sdk: actually call the approve_unverified_tx step

---

.github/workflows/ci-test.yaml
client-sdk/ts-web/core/jest.config.js
client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/playground/webpack.config.js
client-sdk/ts-web/core/src/hdkey.ts
client-sdk/ts-web/core/src/index.ts
client-sdk/ts-web/core/test/adr-0008-vectors.json
client-sdk/ts-web/core/test/hdkey.test.ts
client-sdk/ts-web/core/tsconfig.json
client-sdk/ts-web/jest.config.js
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/package.json
client-sdk/ts-web/rt/playground/webpack.config.js
client-sdk/ts-web/signer-ledger/playground/webpack.config.js

Rework of #65 to use SLIP-0010 instead of BIP32-ED25519
Implements [ADR 0008: Standard Account Key Generation](https://github.com/oasisprotocol/oasis-core/pull/3656/) in ts-web/core, standardizing the key generation process using [BIP-0039] to generate the seed, and [SLIP-0010] for hierarchical deterministic key generation. 
The value proposition mentioned in [ADR 0008] is as follows : 
> Adopting these standards will allow the Oasis ecosystem to:
> 
> - Make key derivation the same across different applications (i.e. wallets).
> - Allow users to hold keys in hardware wallets.
> - Allow users to hold keys in cold storage more reliably (i.e. using the
familiar 24 word mnemonics).
> - Define how users can generate multiple keys from a single seed (i.e.
the 24 or 12 word mnemonic).
We add a …

ts-web/core: ADR 0008 implementation for ts-web

---

.github/workflows/ci-longtest.yaml
tests/consts.sh
tests/download-artifacts.sh
tests/e2e/go.mod
tests/e2e/runtime.go
tests/e2e/scenarios.go
tests/e2e/simple_consensus.go
tests/e2e/simplekvtest.go
tests/e2e/simplekvtest_txgens.go
tests/e2e/txgen/generators.go
tests/e2e/txgen/txgen.go
tests/run-e2e.sh
tests/runtimes/simple-keyvalue/src/lib.rs

Closes #50.
This PR adds a reusable random transaction generator to the e2e tests.
Currently, an e2e test uses the transaction generator to generate random transactions and queries for the `simple-keyvalue` runtime (including transfers between accounts) for 1 minute and then stops.
A separate long-term test that generates random transactions and queries for 15 minutes is scheduled to run once per day at midnight UTC.

tests/e2e: Add transaction generator

---

client-sdk/ts-web/core/.gitignore
client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/tsconfig.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/.gitignore

Here's the preparation for releasing @oasisprotocol/client version 0.1.0-alpha2.
It's desired that we make a release with the new ADR 0008 implementation.
If we accept this, I'll build on master and upload to npm.
`npm pack --dry-run` output:
```
npm notice 
npm notice 📦  @oasisprotocol/client@0.1.0-alpha2
npm notice === Tarball Contents === 
npm notice 2.2kB  README.md           
npm notice 285B   dist/address.d.ts   
npm notice 945B   dist/address.js     
npm notice 1.3kB  dist/beacon.d.ts    
npm notice 1.7kB  dist/beacon.js      
npm notice 23.7kB dist/client.d.ts    
npm notice 41.8kB dist/client.js      
npm notice 2.7kB  dist/common.d.ts    
npm notice 3.5kB  dist/common.js      
npm notice 4.1kB  dist/consensus.d.ts 
npm notice 5.7kB  dist/consensus.js   
npm notice 342B …
```

ts-web/core: version 0.1.0-alpha2

---

runtime-sdk/src/context.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/lib.rs
runtime-sdk/src/module.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs
runtime-sdk/src/modules/consensus/mod.rs
runtime-sdk/src/modules/consensus/test.rs
runtime-sdk/src/modules/consensus_accounts/mod.rs
runtime-sdk/src/modules/consensus_accounts/test.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/modules/rewards/mod.rs
runtime-sdk/src/modules/rewards/test.rs
runtime-sdk/src/runtime.rs
runtime-sdk/src/testing/mock.rs
runtime-sdk/src/types/message.rs
tests/runtimes/simple-keyvalue/src/keyvalue.rs

Refactors the way method dispatch is performed by removing the method
registries and replacing them with static dispatch in the form of a
MethodHandler trait which needs to be provided by modules.
Additionally the contexts are made more composable by making sure that
the we take Context as a generic type argument everywhere and improving
the way simulation mode is handled.
Each context is now also bound to a specific Runtime type to allow for
nested method dispatch.

runtime-sdk: Static call/query/message result handler dispatch

---

README.md
client-sdk/ts-web/core/docs/getting-started.md

notably, this adds a shorter 'getting started' section for the @oasisprotocol/client package that uses the public oasis-node + Envoy server

docs adjustments

---

client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/src/address.ts
client-sdk/ts-web/package-lock.json

this is what it would look like. seems like they added a bech32m implementation.
although this does take us out of sync with @oasisprotocol/ledger :thinking: 
manual version of #174

ts-web/core: bech32 2.0.0

---

runtime-sdk/src/dispatcher.rs
runtime-sdk/src/module.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/types/transaction.rs

This was useful for me to determine that txs require at least one signature, but I don't really know why that's true.

Add context to error messages

---

Cargo.lock
README.md
docs/guide/getting-started.md
runtime-sdk/Cargo.toml
tests/consts.sh

To prevent confusion about which version works on the testnet.

runtime-sdk: bump oasis-core-runtime version

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json

Our samples' webpack configs are written for webpack-dev-server 4. Add that to our package.json.
Previously this worked by npm installing this for the outer workspace from other packages' requests. This is more explicit.

ts-web/ext-utils: fix webpack-dev-server version

---

.github/workflows/ci-lint.yml
.github/workflows/ci-test.yaml

fixes #291 
seems npm now runs 'lifecycle scripts' during workspace install https://github.com/npm/cli/issues/2900 https://github.com/npm/arborist/commit/5a4c1062aa7d0ca228fca20c6835a6a26e434f89. from convenient, no? we save a few `npm run prepare` steps.
but it does kind of a shoddy job of it. it runs all the packages' `prepare` scripts at the same time, concurrently. however, other dev tools we use, such as tsc, rely on dependencies already being built, so this broke things for us.
for now, we manually encode that `core` is lower (?) in the dependency graph and manually do that first. then we install the other packages, although I'm pretty sure that recompiles `core` :roll_eyes:

ci: install ts-web/core package first

---

.dockerignore
tests/benchmark/Dockerfile
tests/benchmark/build-benchmarks.sh
tests/benchmark/cmd/fixture.go
tests/benchmark/run-benchmarks.sh

- use release instead of the debug benchmarks build
- use compute+storage worker nodes instead of separate workers
- bump some benchmark parameters

test/benchmark: fixes and improvements

---

runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/testing/mock.rs
tests/benchmark/run-benchmarks.sh

With https://github.com/oasisprotocol/oasis-core/pull/4131 oasis-core will be scheduling CheckTx batches. The runtime scheduler cannot enforce batch-limits for non-checked transactions, therefore the runtime should not enforce these either.
Other batch limits (emitted messages, batch size) are already not enforced for check-tx batches.

runtime-sdk/core: do not enforce batch gas limit for CheckTx

---

client-sdk/ts-web/ext-utils/sample-ext/src/index.js
client-sdk/ts-web/ext-utils/sample-page/src/index.js

This PR adds some sample code demonstrating how to use the ext-utils interfaces with some simplifications:
- in a dapp, how to receive the new keys list whenever the keys list changes
- in an extension, how to serve both `keysList` and `contextSignerPublic` with a single key list implementation (cross-reference #287 )

ts-web/ext-utils: adapters around the interface

---

.github/workflows/ci-lint.yml
.github/workflows/ci-test.yaml

fixes #315 
this is pretty alright. now it knows to do core first

ci: use --foreground-scripts to coordinate install order

---

.github/workflows/docker.yml
tests/benchmark/Dockerfile

Fixes the benchmarks image build when runtime-sdk depends on a unreleased oasis-core version

benchmarks: fix docker image build

---

client-sdk/ts-web/core/playground/sample-envoy.yaml
client-sdk/ts-web/ext-utils/src/ext.ts

1. clarify that `oasisExt.ext` communicates with a single web page that embeds an instance of oasis-xu-frame.html
2. add `expose_headers` to sample envoy config, without which grpc errors aren't shown to the client
3. add [debonding] delegation infos to allowed methods in sample envoy config because they're easy to misspell

Documentation materials improvements

---

client-sdk/ts-web/ext-utils/docs/changelog.md
client-sdk/ts-web/ext-utils/sample-ext/src/index.js
client-sdk/ts-web/ext-utils/sample-page/src/index.js
client-sdk/ts-web/ext-utils/src/ext.ts
client-sdk/ts-web/ext-utils/src/protocol.ts

add a field for the new keys. the extension now has to provide this when it tells the web content that the keys list has changed

ts-web/ext-utils: keys change event with keys list

---

client-sdk/go/client/client.go

client-sdk/go: Use GetTransactions instead of deprecated GetTxs

---

client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/src/transaction.ts
client-sdk/ts-web/rt/src/wrapper.ts

this adds doc comments to some ts-web-specific API elements. notably, with the signing design being different from how it works in go, we could use this extra info

ts-web/rt: doc comments for signing

---

docker/runtime-builder/Dockerfile

This should fix https://github.com/oasisprotocol/oasis-sdk/runs/3487648229

runtime-builder/Dockerfile: use --locked when installing oasis-core tools

---

runtime-sdk/modules/contracts/src/abi/oasis/test.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/src/modules/accounts/test.rs
tests/contracts/hello/Cargo.lock
tests/contracts/hello/src/lib.rs
tests/e2e/contracts.go

Adds support for setting an initial contract value to the `hello` contract, as an example for initializing contract state.

hello-contract: support for setting initial counter

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/src/types.ts

detected some mismatches from the generated types from #90 
- some `omitempty` fields aren't marked as optional
- consensus `Parameters.MaxEvidenceSize` is uint64, so it should be longnum. I probably missed this when I was replacing MaxEvidenceNum. in practice it's 51200, so the difference never came up
- the lexicographical ordering between Signature and SignatureMultiSigned was swapped. possibly related to Signature having been collapsed from SignatureSignature :shrug: 
~~also I'm changing `toarray` structs to be multiline (only `StorageLogEntry` at this time). lint, please don't kill me~~ nvm lint did kill me

ts-web/core: minor types fixes

---

client-sdk/ts-web/core/src/types.ts

further discrepancies with a newly expanded generated types set
- `OpenExecutorCommitment` is serialized as `ExecutorCommitment`, which we further lower to `Signed`. not `ComputeBody` as incorrectly specified before
- a couple of structs were out of order
reopened from #410

ts-web/core: minor types sync

---

Cargo.lock
contract-sdk/src/abi/env.rs
contract-sdk/src/env.rs
contract-sdk/src/testing.rs
contract-sdk/types/Cargo.toml
contract-sdk/types/src/address.rs
runtime-sdk/modules/contracts/src/abi/oasis/env.rs
runtime-sdk/modules/contracts/src/abi/oasis/memory.rs
runtime-sdk/modules/contracts/src/test.rs
tests/contracts/hello/Cargo.lock
tests/contracts/hello/src/lib.rs

Adds `address_for_instance` function to the wasm contracts environment

contracts-sdk: add env.address_for_instance function

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/src/client.ts
client-sdk/ts-web/core/src/registry.ts
client-sdk/ts-web/core/src/types.ts
client-sdk/ts-web/core/src/upgrade.ts

Here are the remaining discrepancies between the automatically generated types from #90 and our current type definitions. A this point, I'd like to apply all of them as changes.
- Breaking: NodeAddress is changed to NetTCPAddr, which is consistent with everywhere else where we use the least-derived equivalent type.
- We're synced up with the changes from the oasis-core side. These we don't include in the changelogs. Including but not limited to:
- beacon consensus module removal
- runtime client changes
- Slices of special `uint8` are corrected to be `Uint8Array` instead of `number[]`.
- Some mistakes in porting the types are corrected.
- Some mistakes in transferring the doc comments are corrected.
- Uppercase tuple element names from `toarray` structs are now preserved instead of being …

ts-web/core: types fixes and sync chnages from oasis-core

---

client-sdk/ts-web/core/reflect-go/go.mod
client-sdk/ts-web/core/reflect-go/go.sum

to 425f2a41f, with the rest of the repo
no API changes during that range

ts-web/core: reflect match oasis-core version with go sdk

---

client-sdk/ts-web/core/README.md

We added the `catch` described in the README here to the client in 265be7f992dae7fa291389865bd29be2306d68d8

ts-web/core: remove obsolete caveat from readme

---

runtime-sdk/modules/contracts/src/results.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/modules/contracts/src/types.rs

Fixes #457 
This allows the module to include additional metadata like the instance
identifier of the contract that emitted the given event.

runtime-sdk/modules/contracts: Wrap contract events

---

.github/actions/lint-rust/action.yml
.github/actions/test-rust/action.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-test.yaml
Cargo.lock
Cargo.toml
client-sdk/go/modules/contracts/contracts_test.go
client-sdk/go/modules/contracts/oas20/oas20.go
client-sdk/go/modules/contracts/oas20/oas20_test.go
client-sdk/go/modules/contracts/types.go
client-sdk/go/types/address.go
client-sdk/go/types/address_test.go
contract-sdk/specs/oas20/README.md
contract-sdk/specs/oas20/contract/Cargo.lock
contract-sdk/specs/oas20/contract/Cargo.toml
contract-sdk/specs/oas20/contract/src/lib.rs
contract-sdk/specs/oas20/types/Cargo.toml
contract-sdk/specs/oas20/types/src/lib.rs
contract-sdk/specs/oas20/types/src/test.rs
contract-sdk/src/testing.rs
contract-sdk/types/src/address.rs
contract-sdk/types/src/lib.rs
contract-sdk/types/src/testing.rs
runtime-sdk/modules/contracts/src/lib.rs
runtime-sdk/modules/contracts/src/types.rs
runtime-sdk/src/types/address.rs
tests/contracts/hello/Cargo.toml
tests/contracts/hello/src/lib.rs
tests/e2e/contracts.go
tests/run-e2e.sh

ERC-20/CW-20 like spec for contracts-sdk with an example implementation
TODO:
- probably not needed for now, can add it later in a non-breaking way (as optional extensions)

OAS20 spec

---

contract-sdk/specs/oas20/contract/src/lib.rs
contract-sdk/specs/oas20/types/src/helpers.rs
contract-sdk/specs/oas20/types/src/lib.rs
contract-sdk/src/testing.rs
contract-sdk/types/src/lib.rs
contract-sdk/types/src/message.rs
contract-sdk/types/src/modules/contracts.rs
contract-sdk/types/src/modules/mod.rs
runtime-sdk/modules/contracts/src/abi/oasis/test.rs
runtime-sdk/modules/contracts/src/results.rs
runtime-sdk/src/context.rs
tests/contracts/hello/src/lib.rs
tests/e2e/contracts.go

-  add support for passing optional data to contract `reply_handlers`
- extract OAS20 methods logic to `types` crate helpers functions, so that these can be reused in contracts extending the OAS20-base (e.g.  creating a wrapped-oas20 token contract)
- add E2E test to `hello` contract for initializing a OAS20 token via the `hello` contract

contract-sdk: updates / improvements

---

runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs
runtime-sdk/src/crypto/signature/secp256k1.rs
tests/e2e/simpleevmtest.go

hash it the way ethereum does, so we can get an ethereum address from a secp256k1 key
wanted in #452

modules/evm: ethereum-compatible secp256k1 addresses

---

runtime-sdk/modules/evm/src/derive_caller.rs
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs

~~adds a new ...from_public_key, for tests were we don't have an entire auth_info struct~~ partially split into #491 
extract some smaller common logic
moves these to a new mod so that we don't have to configure an entire evm module to use it. mostly for testing
wanted for #452

modules/evm: refactor derive_caller_*

---

runtime-sdk/modules/evm/src/evm_backend.rs
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs
tests/runtimes/simple-evm/src/lib.rs

Take the chain ID from a configuration const. We'd like to be able
to use small numbers.

modules/evm: new chain_id implementation

---

Cargo.lock
runtime-sdk/modules/evm/Cargo.toml
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/raw_tx.rs

This introduces a module-controlled transaction decoding scheme, `evm.ethereum.v0`. this parses and verifies an Ethereum "sendRawTransaction" compatible transaction.
For implementation, we're using some structs from the `ethereum` crate, which seems to be related to our choice of evm implementation. But that crate was buggy, and several things we ended up having to do ourselves.

ethereum transaction decoding

---

contract-sdk/specs/oas20/contract/src/lib.rs
contract-sdk/specs/oas20/types/src/helpers.rs
contract-sdk/storage/src/map.rs

- adds `handle_query` and `handle_call` methods to OAS20 helpers, so that standard handling of OAS20 requests can be easily reused. The per-call helpers are also kept, as those might be useful for contracts implementing only parts of the OAS20 spec 
- implements `MapKey` for byte arrays

OAS20 request handler helpers

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json

the new oasis-core 21.3 will need these changes we made to the runtime transaction request/response bodies, where they changed from nested CBOR structures to flat byte arrays
a release to get that new functionality out to developers

ts-web/rt: v0.2.0-alpha4

---

client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/src/wrapper.ts

people were saying SubmitTxNoWait was good, so let's add that to the transaction wrapper. no way to get the transaction result this way though.
no tests
reopening from #558

ts-web/rt: add SubmitTxNoWait to transaction wrapper

---

contract-sdk/specs/oas20/contract/src/lib.rs
contract-sdk/src/abi/crypto.rs
contract-sdk/src/abi/dispatch.rs
contract-sdk/src/abi/env.rs
contract-sdk/src/abi/mod.rs
contract-sdk/src/abi/storage.rs
contract-sdk/src/memory.rs
runtime-sdk/modules/contracts/src/abi/oasis/env.rs
runtime-sdk/modules/contracts/src/abi/oasis/memory.rs
runtime-sdk/modules/contracts/src/abi/oasis/mod.rs
runtime-sdk/modules/contracts/src/abi/oasis/storage.rs
runtime-sdk/modules/contracts/src/abi/oasis/test.rs
tests/contracts/hello/src/lib.rs

The WASM abi seems quite broken, there are various problems with it:
- problems with u128 https://github.com/rust-lang/rust/issues/88207
- problems with compiling multivalue functions https://github.com/ptrus/wasm-bug
Switch to using C abi. This requires modifying the exported functions to not use multivalue returns (which was only used for returning `HostRegion`s currently).

contract-sdk: use C abi instead of wasm

---

Cargo.lock
client-sdk/go/client/client.go
client-sdk/go/go.mod
client-sdk/go/go.sum
client-sdk/ts-web/core/reflect-go/go.mod
client-sdk/ts-web/core/reflect-go/go.sum
runtime-sdk/Cargo.toml
tests/benchmark/go.mod
tests/benchmark/go.sum
tests/consts.sh
tests/e2e/go.mod
tests/e2e/go.sum
tests/e2e/scenarios.go
tests/e2e/simplekvtest.go

Blocked on support in Oasis Core, see https://github.com/oasisprotocol/oasis-core/issues/4334.

client-sdk/go: Add support for GetLastRetainedBlock query

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json

We want to start using the ethereum-compatible addresses in downstream wallet projects.

ts-web/rt: v0.2.0-alpha5

---

client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/accounts/types.go
client-sdk/go/modules/consensus/consensus.go
client-sdk/go/modules/consensus/types.go
client-sdk/ts-web/rt/playground/src/consensus.js
client-sdk/ts-web/rt/src/accounts.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/src/lib.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs
runtime-sdk/src/modules/accounts/types.rs
runtime-sdk/src/modules/consensus/mod.rs
runtime-sdk/src/modules/consensus/test.rs
runtime-sdk/src/modules/consensus_accounts/mod.rs
tests/e2e/simple_consensus.go
tests/runtimes/simple-consensus/src/lib.rs

runtime-sdk: Support consensus denomination scaling

---

client-sdk/ts-web/package-lock.json
client-sdk/ts-web/signer-ledger/docs/changelog.md
client-sdk/ts-web/signer-ledger/package.json

this is so we can start using @oasisprotocol/ledger v2.x downstream

ts-web/signer-ledger: v0.1.0-alpha3

---

runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs

This is needed for migrations that scale base units.

modules/accounts: Add internal method for setting total supply

---

runtime-sdk/src/modules/core/mod.rs

Could further limit this by a runtime configuration parameter. (can open an issue for it)

estimateGas: limit gas to the maximum batch gas limit

---

client-sdk/go/modules/core/core.go
client-sdk/go/modules/core/types.go
client-sdk/go/testing/testing.go
client-sdk/go/testing/testing_test.go
client-sdk/go/types/transaction.go
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/modules/contracts/src/results.rs
runtime-sdk/modules/evm/src/derive_caller.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/modules/core/types.rs
runtime-sdk/src/types/transaction.rs
tests/e2e/simpleevmtest.go
tests/e2e/simplekvtest.go

Adds support for specifying an ETH caller address in `EstimateGas`. This way `evm` module can derive the correct caller from the address. 
Before this change all `EstimateGas` requests for evm transactions were failing at the `derive_caller` step: https://github.com/oasisprotocol/oasis-sdk/blob/6f2ce9f81d41f8a394dd8490016ed6f73042338b/runtime-sdk/modules/evm/src/lib.rs#L237
TODO:

EstimateGas: support ETH caller address

---

client-sdk/go/modules/consensusaccounts/types.go
client-sdk/ts-web/rt/src/consensus_accounts.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/src/modules/consensus_accounts/mod.rs
runtime-sdk/src/modules/consensus_accounts/test.rs
runtime-sdk/src/modules/consensus_accounts/types.rs
tests/e2e/simple_consensus.go

This is a PR replacing the synthetic withdraw/deposit ID (used to correlate a success/fail event with a transaction) with the sender's nonce. Then the sender and the nonce together should uniquely identify the operation.
We discussed this, and we liked that this way doesn't introduce its own state. Also clients won't need to wait for the transaction response this way.
Initiating a deposit/withdraw is part of the module's API. If we go on to use this in cases other than directly from these transactions, then the caller should come up with its own way of using this nonce. It should be okay as long as there aren't multiple identical deposits generated from a single outermost transaction. :shrug:

modules/consensus_accounts: substitute nonce for id in events

---

client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/playground/src/consensus.js

let's make it not start polling until the tx submission succeeds, after all.
this makes us more flexible if we later do something that needs the tx result to poll. but in the big picture, this polling is because we kind of don't want to have long lived connections to the grpc-web proxy :shrug:. the manual polling allows us to read up from a known starting point, beginning from a later time. the real streaming APIs don's support this, so it's also good that we don't need the tx result.
and there's a little added thing that makes it poll fast until the first 'block not found' response, in case it takes a while to submit and multiple blocks come out during that time.
changes are to sample/test code only, no need for a new release

ts-web/rt: playground don't poll if tx submission fails

---

client-sdk/go/client/client.go
client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/contracts/oas20/oas20.go
client-sdk/go/modules/evm/evm.go
client-sdk/ts-web/rt/src/event.ts
runtime-sdk/modules/contracts/src/results.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/src/context.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/event.rs
runtime-sdk/src/modules/consensus_accounts/test.rs
runtime-sdk/src/modules/core/test.rs
tests/e2e/simple_consensus.go
tests/e2e/simplekvtest.go

Currently, the way sdk-events are mapped into tags causes the events of the same type to override and only the last emitted event is actually emitted as a transaction tag. 
For example, currently only the last emitted EVM log is emitted as a transaction tag and others are lost  https://github.com/oasisprotocol/oasis-sdk/blob/f5b7a5429342770dbf0ea464854cd9be49d03bd1/runtime-sdk/modules/evm/src/backend.rs#L250-L257
This changes the way events are mapped into transaction tags. The tag value is now an array of events.
Clients:

Fix emitting multiple of events of the same type

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/rt/src/event.ts

we'd like to get this out to developers now that Emerald on testnet is upgraded to a new version with the array-type events

ts-web/rt: v0.2.0-alpha10

---

client-sdk/ts-web/core/src/client.ts

we'll put it in the stack after all. and if something crazy happens like `.stack` is not settable, what's it gonna do? throw an error at a time where we want it to throw an error? :hand_over_mouth: 
cc @lukaw3d on the design

ts-web/core: client error wrapping changes

---

client-sdk/ts-web/core/playground/sample-envoy.yaml

Envoy is moving this to a so-called "runtime" configuration.

ts-web/core: migrate re2 max_program_size

---

Cargo.lock
runtime-sdk/modules/evm/Cargo.toml

Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/710
Uses: https://github.com/oasisprotocol/evm/tree/v0.33.1-oasis

runtime-sdk/evm: update evm crate to include the gas estimate fix

---

Cargo.lock
cli/go.mod
cli/go.sum
client-sdk/go/go.mod
client-sdk/go/go.sum
client-sdk/go/types/transaction.go
client-sdk/ts-web/core/reflect-go/go.mod
client-sdk/ts-web/core/reflect-go/go.sum
runtime-sdk/Cargo.toml
runtime-sdk/src/modules/accounts/test.rs
tests/benchmark/go.mod
tests/benchmark/go.sum
tests/consts.sh
tests/e2e/go.mod
tests/e2e/go.sum
tests/e2e/scenarios.go
tests/e2e/simplekvtest.go
tests/e2e/txgen/txgen.go
tests/runtimes/simple-keyvalue/src/lib.rs

Inspired by #738.
Also bumps Oasis Core to 21.3.8 as otherwise the test wouldn't pass due to the query returning incorrect results.

tests/e2e: Add test for transaction ordering by priority

---

client-sdk/ts-web/core/src/client.ts

y'all, mistakes were made
we haven't permitted roothash on our public grpc-web proxy, so nothing was using these misspelled methods that we know of

ts-web/core: fix rootHash spelling

---

client-sdk/ts-web/core/playground/src/errata/inquire.js
client-sdk/ts-web/core/playground/webpack.config.js
client-sdk/ts-web/ext-utils/sample-ext/src/errata/inquire.js
client-sdk/ts-web/ext-utils/sample-ext/webpack.config.js
client-sdk/ts-web/ext-utils/sample-page/src/errata/inquire.js
client-sdk/ts-web/ext-utils/sample-page/webpack.config.js
client-sdk/ts-web/rt/playground/src/errata/inquire.js
client-sdk/ts-web/rt/playground/webpack.config.js
client-sdk/ts-web/signer-ledger/playground/src/errata/inquire.js
client-sdk/ts-web/signer-ledger/playground/webpack.config.js

protobufjs's 'inquire' library will always fail
not sure if we should really merge this:
- it's really downstream users that will need to do this
- this particular 'playground' page runs in dev mode with the 'eval devtool' anyway
cc #608

ts-web/core: playground show how to avoid eval

---

cli/cmd/contracts.go

This PR:
* Makes `data` a required argument to call and instantiate. In almost all cases, the contract will have args, and when it doesn't, it's possible to recover the previous behavior by passing the empty string. In the common case, making the param required will prevent people from being confused by errors like `execution failed: unreachable executed` resulting from failing to provide request data (maybe `Instantiate` is some magic added by the SDK? who knows).
* Clarifies in the help message that `data` is YAML-encoded.
* Removes a spurious alias (call and inst are not the same command).

cli: clarify call/instantiate args

---

contract-sdk/Cargo.toml
contract-sdk/src/abi/env.rs
contract-sdk/src/env.rs
contract-sdk/src/testing.rs
runtime-sdk/modules/contracts/Cargo.toml
runtime-sdk/modules/contracts/src/abi/oasis/env.rs
runtime-sdk/modules/contracts/src/lib.rs

This PR:
* adds a `debug_print` method for inspecting the state of the contract
* makes methods on `Module` public so that third parties can programmatically invoke the environment (I copied over the e2e tests from this repo to my own crate, with good results)

Add debugging niceties

---

client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/core/core.go
client-sdk/go/modules/evm/evm.go

This is useful when you already have raw events that you want to decode (e.g. obtained via `TransactionWithResults`) and no runtime client.

client-sdk/go: add package DecodeEvent methods

---

.github/workflows/benchmarking-image.yml
.github/workflows/ci-audit.yml
.github/workflows/ci-docs.yaml
.github/workflows/ci-lint.yml
.github/workflows/ci-reproducibility.yml
.github/workflows/ci-test.yaml
.github/workflows/runtime-builder-image.yml

Default behavior is that in-progress runs are not canceled (e.g. when pushing new changes to a branch).

ci: cancel concurrent in-progress workflows on same branch

---

Cargo.lock
client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/accounts/types.go
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/consensusaccounts/types.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/contracts/types.go
client-sdk/go/modules/core/core.go
client-sdk/go/modules/core/types.go
client-sdk/go/modules/evm/evm.go
client-sdk/go/modules/evm/types.go
runtime-sdk-macros/src/method_handler_derive.rs
runtime-sdk/src/modules/consensus/mod.rs
runtime-sdk/src/modules/rewards/mod.rs
tests/e2e/contracts.go
tests/e2e/scenarios.go
tests/e2e/simple_consensus.go
tests/e2e/simpleevmtest.go
tests/e2e/simplekvtest.go

runtime-sdk-macros: automatically implement parameters query handler

---

runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs

Special case empty revert reason, so that instead of: `invalid reason prefix: ''` we return `no revert reason`

evm: handle empty revert reason

---

client-sdk/go/modules/core/core.go
client-sdk/go/modules/core/types.go
client-sdk/ts-web/rt/playground/src/index.js
client-sdk/ts-web/rt/src/core.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk-macros/src/method_handler_derive.rs
runtime-sdk/src/module.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/modules/core/types.rs
runtime-sdk/src/runtime.rs
tests/e2e/scenarios.go
tests/e2e/simplekvtest.go

Resolves #652 .
Adds a new `core.RuntimeInfo` query to the `core` module which provides basic information about the runtime and the modules it contains. See the bottom of `core/test.rs` for sample output.

Introspection endpoint for Core module

---

Cargo.lock
cli/wallet/ledger/signer.go
client-sdk/go/crypto/signature/ed25519/signer.go
client-sdk/go/crypto/signature/secp256k1/signer.go
client-sdk/go/crypto/signature/signer.go
client-sdk/go/crypto/signature/sr25519/signer.go
client-sdk/go/modules/contracts/types.go
contract-sdk/Cargo.toml
contract-sdk/specs/oas20/Cargo.lock
contract-sdk/src/abi/crypto.rs
contract-sdk/src/abi/env.rs
contract-sdk/src/env.rs
contract-sdk/src/testing.rs
contract-sdk/types/src/crypto.rs
contract-sdk/types/src/lib.rs
runtime-sdk/modules/contracts/src/abi/oasis/crypto.rs
runtime-sdk/modules/contracts/src/abi/oasis/env.rs
runtime-sdk/modules/contracts/src/abi/oasis/mod.rs
runtime-sdk/modules/contracts/src/lib.rs
runtime-sdk/src/crypto/signature/ed25519.rs
runtime-sdk/src/crypto/signature/mod.rs
runtime-sdk/src/crypto/signature/secp256k1.rs
tests/contracts/hello/Cargo.lock
tests/contracts/hello/src/lib.rs
tests/e2e/contracts.go

contract-sdk: Expose signature verification to wasm contracts

---

cli/wallet/ledger/ledger.go

Default oasis cli derivation path on ledger is currently ADR8 and is inconsistent with Oasis web/ext wallets. This PR defaults to legacy, so we avoid issues when users don't see correct accounts and balances using defaults.

cli: Default to legacy derivation on ledger

---

runtime-sdk/src/runtime.rs

This is useful so that one is able to run a paratime with migrations on fresh state (e.g. local test network).

runtime-sdk/migrations: allow migrating from empty state

---

client-sdk/go/modules/core/types.go
runtime-sdk/src/config.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/module.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/runtime.rs
tests/runtimes/benchmarking/src/lib.rs
tests/runtimes/simple-consensus/src/lib.rs
tests/runtimes/simple-contracts/src/lib.rs
tests/runtimes/simple-evm/src/lib.rs
tests/runtimes/simple-keyvalue/src/lib.rs
tests/runtimes/simple-keyvalue/src/test.rs

Given upcoming oasisprotocol/oasis-core#4665 which will mandate runtime schedule control, this makes schedule control always enabled.

runtime-sdk: Permanently enable schedule control

---

cli/README.md
cli/cmd/accounts.go
cli/cmd/common/selector.go
cli/cmd/common/transaction.go
cli/cmd/common/wallet.go
cli/cmd/contracts.go
cli/cmd/inspect/governance_proposal.go
cli/cmd/inspect/native_token.go
cli/cmd/inspect/node_status.go
cli/cmd/inspect/runtime_stats.go
cli/cmd/network.go
cli/cmd/paratime.go
cli/cmd/root.go
cli/cmd/wallet.go
cli/config/config.go
cli/config/wallet.go
cli/wallet/file/ed25519.go
cli/wallet/file/file.go
cli/wallet/ledger/ledger.go
cli/wallet/wallet.go

Porting "wallet"-"account" term fixes from [oasis-wallet-web#814 ](https://github.com/oasisprotocol/oasis-wallet-web/pull/814) for consistency:
- Replaces term "wallet" with "account" in command descriptions where applicable
- Renames internal `Wallet` structs with `Account` and `Wallets` with `Wallet`.
- Renamed `--wallet` to `--account`, `--wallet` remains there for backward compatibility
- Shows account name before signing transactions
- Shows `(*)` for default account in `wallet list` output
Some leftovers which this PR doesn't cover, because it affects end users flow too much:
- `wallets.<some_account_name>` field in the config file is intact (should be `accounts.<some_account_name>`, but would break loading the existing wallet)

i18n: Fix usage of term "wallet" instead of "account"

---

client-sdk/ts-web/core/src/client.ts

Example that returns undefined
```ts
await oasisClient.consensusGetSignerNonce({
account_address: oasis.staking.addressFromBech32('oasis1qqqnpm9l8khrj9zaqzmt537gvnx6y38ntsc8jdrh'),
height: 0,
})
```
(And playground already handles undefined return: https://github.com/oasisprotocol/oasis-sdk/blob/037546906fa06cae3983fb6b9b6ebadeaf63ac4e/client-sdk/ts-web/core/playground/src/index.js#L53-L56
)

ts-web: fix consensusGetSignerNonce return type (can be undefined)

---

client-sdk/ts-web/core/reflect-go/main.go
client-sdk/ts-web/core/src/beacon.ts
client-sdk/ts-web/core/src/client.ts
client-sdk/ts-web/core/src/common.ts
client-sdk/ts-web/core/src/registry.ts
client-sdk/ts-web/core/src/roothash.ts
client-sdk/ts-web/core/src/scheduler.ts
client-sdk/ts-web/core/src/staking.ts
client-sdk/ts-web/core/src/storage.ts
client-sdk/ts-web/core/src/types.ts

fixes #822 #922 
- maintaining the list of types from transaction method bodies is too much work, so let's read from the registered methods list. but unfortunately it's unexported, so it's some kind of ugly `go:linkname` thing that I found out the idea of online
up to 22.1.5

ts-web: reflect updates

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/package-lock.json

for compatibility with oasis-core 22.1.x
the API changes are to parts not known to be in widespread use.
there's also a nice typing change for the typescript users

ts-web/core: version 0.1.0-alpha9

---

contract-sdk/specs/oas20/src/helpers.rs
contract-sdk/specs/oas20/src/lib.rs
contract-sdk/src/abi/dispatch.rs
contract-sdk/src/abi/storage.rs
contract-sdk/src/context.rs
contract-sdk/src/storage.rs
contract-sdk/src/testing.rs
contract-sdk/storage/src/cell.rs
contract-sdk/storage/src/map.rs
docs/contract/hello-world.md
tests/contracts/hello/src/lib.rs

This makes it possible to ensure the correct kind of store is used in various places.

contract-sdk: Add marker traits for confidential/public stores

---

cli/cmd/contracts.go
docs/contract/hello-world.md

Also fixes contract deployment instructions as the CLI use has changed recently.

cli: Fix incorrect contracts call data parsing

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/signer-ledger/package.json

0.1.0-alpha9 is out
during development, these are linked in a workspace, so they always use the version in the repo. bumping the version in the released one ensures that external projects using these libraries have consistent versions

ts-web: update core dependency

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/docs/getting-started.md
client-sdk/ts-web/ext-utils/docs/changelog.md
client-sdk/ts-web/rt/docs/changelog.md

that getting-started doc was way out of date
- client class has moved
- public node urls changed
- our sample now uses the cors way

ts-web: docs updates

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/signer-ledger/package.json

typescript changes from #790 
turns out the `-alpha9` thing was not the prerelease format that npm's semver supports. moving on to 0.1.0-alpha10 would be treated as a lower version. we're correcting this to the supported `-alpha.10` style and bumping the patch version

ts-web/core: v0.1.1-alpha.1

---

client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json

typescript changes from #790
turns out we had additions from before, which we never made a release since. using those as the spotlight change
the version numbering is updated, see #948

ts-web/rt: v0.2.1-alpha.1

---

client-sdk/ts-web/ext-utils/docs/changelog.md
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json

typescript changes from #790
the version numbering is updated, see #948

ts-web/ext-utils: v0.1.1-alpha.1

---

docs/contract/getting-started.md
docs/runtime/getting-started.md

Fixes regression introduced in f41342b1d68da4cffbb1fac3b97be6dd8022d318. Also needs backport to 0.2.x.

docs: Fix broken links

---

Cargo.lock
runtime-sdk/modules/evm/Cargo.toml
runtime-sdk/modules/evm/src/lib.rs

The most notable change is that `transact_create` now also propagates the error in case of deploy contract failure (https://github.com/rust-blockchain/evm/pull/91). Which also makes this a breaking change (unless we would not want to propagate the error).
Other than that, seems mostly dependency bumps.

runtime-sdk/evm: bump evm (breaking)

---

.github/actions/hash-rust/action.yml

For me, this is to allow `rustup target add x86_64-fortanix-unknown-sgx` before building, as I cannot have a `rust-toolchain.toml` auto-install it because [actions-rs does not support it](https://github.com/actions-rs/toolchain/pull/209).

ci: allow passing setup code to hash-rust

---

.github/actions/test-rust/action.yml
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/types/transaction.rs

Adds configurable gas estimation via binary search support. 
Enables fixing some EVM edge cases (https://github.com/oasisprotocol/oasis-sdk/issues/631) where gas estimation depends on actual gas limit used during estimation.
There are some EVM "gotcha's", hopefully the comments explain it well enough.

runtime-sdk: gas estimate binary search

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
contract-sdk/types/Cargo.toml
runtime-sdk/Cargo.toml
runtime-sdk/modules/contracts/Cargo.toml
runtime-sdk/modules/evm/Cargo.toml
tests/contracts/hello/Cargo.lock

`cargo update` & some manual updates that were straightforward (required no code changes).

runtime-sdk: bump dependencies

---

docs/contract/confidential-smart-contract.md
docs/contract/hello-world.md
docs/runtime/getting-started.md
docs/runtime/minimal-runtime.md

Current minimal-runtime tutorial is broken. It works with oasis-core 21.2.x only (and not 21.3.x, because of the missing `span_context` fields!). This PR bumps the dependencies and the example code in rust to match oasis-core 22.1.8 and oasis-sdk post-0.2.0 which is not released yet (currently it will use the `main` branch of oasis-sdk repo).
PR also adds a new subsection on how to connect and send tokens from/to minimal runtime with Oasis CLI.
Preview:
https://github.com/oasisprotocol/oasis-sdk/blob/matevz/docs/bump-runtime-tutorial/docs/runtime/minimal-runtime.md
To be merged **after oasis-core 22.1.8 is released** which contains https://github.com/oasisprotocol/oasis-core/pull/4808 and https://github.com/oasisprotocol/oasis-core/pull/4813.

docs: Refresh minimal-runtime.md

---

cli/cmd/contracts.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/contracts/types.go
client-sdk/ts-web/rt/src/contracts.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/modules/contracts/src/code.rs
runtime-sdk/modules/contracts/src/lib.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/modules/contracts/src/types.rs

- Adds `contracts.CodeStorage` to runtime API which returns the stored Wasm code.
- Updates client-sdk/go bindings.
- Updates client-sdk/ts-web bindings
- Implements it in oasis CLI (`oasis contracts dump-code`).

cli: Add support for dumping deployed WASM of contracts

---

cli/cmd/accounts.go
cli/cmd/common/selector.go
cli/cmd/common/wallet.go
cli/cmd/contracts.go
cli/cmd/wallet.go
cli/wallet/test/test.go
client-sdk/go/helpers/address.go
client-sdk/go/helpers/address_test.go
client-sdk/go/testing/testing.go
docs/runtime/minimal-runtime.md

Fixes #891.
This PR adds the following to `oasis accounts` command:
- if address equals account name in the wallet, it returns the address corresponding to the account
- if address starts with `test:`, it finds the corresponding testing account (Alice, Bob, Charlie etc.) and returns the testing account address
- if `--account` value starts with `test:`, it takes the testing account key to sign the transaction
- updates minimal-runtime docs accordingly
- fixes crash when calling `oasis accounts withdraw <amount> [to]` without `to` parameter
Example usage:
```
$ oasis accounts show mywallet
Address: oasis1qqgwegnh3h6p0828npmqed0f243fd9pyhcgmmmt4
Nonce: 0
=== CONSENSUS LAYER (testnet) ===
Total: 0.0 TEST
Available: 0.0 TEST
$ oasis accounts show test:bob
Address: …
```

cli: Lookup address by account name, add support for test accounts

---

docs/contract/hello-world.md

Running docker on Apple M1 doesn't give you virtualization of x86_64 hardware, but still runs aarch64.

docs: Fix information about running docker test on Apple M1

---

tools/gen_runtime_vectors/README.md
tools/gen_runtime_vectors/main.go
tools/gen_runtime_vectors/testvectors.go

As part of [ADR 14](https://github.com/oasisprotocol/adrs/blob/matevz/adrs/0014/0014-runtime-signing-tx-with-hardware-wallet.md).

docs: Add README.md for tools/gen_runtime_vectors

---

runtime-sdk/modules/evm/src/backend.rs
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs

This PR enables native token transfers from MetaMask (or any other unmodified client). ~It also allows constifying some gas costs/storage ops†.~
~There's another question of whether confidential EVM should pass through txs that fail to decrypt, assuming that they're not encrypted. That's not super safe for least reason of which that it won't be rejected by the client node before the entire network sees the plaintext.~
~† I don't think that we should enable these by default since they're possible for the application/client to mitigate, leaving applications that don't need/care about it lower costs. It's left as a config option just in case (and for others who may wish to use the module).~
* ~the difference between non-zero/zero values in tx data can be fixed by~
- ~having the call contain …

evm: don't require encryption of empty string

---

cli/cmd/contracts.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/contracts/types.go
client-sdk/ts-web/rt/src/contracts.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/modules/contracts/src/lib.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/modules/contracts/src/types.rs
tests/e2e/contracts.go
tools/gen_runtime_vectors/main.go

contracts: support changing contract upgrades policy

---

runtime-sdk/modules/contracts/src/results.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/src/context.rs
runtime-sdk/src/modules/core/mod.rs
tests/contracts/hello/src/lib.rs

Previously various gas and fee checks were performed even for internal
subcalls (e.g. when smart contracts called into other modules) which
was wrong and also caused failures due to minimum gas price not being
met (the fee is always set to zero for subcalls).

runtime-sdk/modules/contracts: Fix subcall dispatch

---

client-sdk/go/modules/evm/signed_calls.go
client-sdk/go/modules/evm/signed_calls_test.go
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/signed_call.rs
runtime-sdk/modules/evm/src/types.rs
runtime-sdk/src/callformat.rs
tests/e2e/evmtest.go

Previously, the entire signed query was encoded into the `data` field and then encrypted, which makes it very difficult for tools and middleboxes to examine public data. This PR modifies the signed query format such that only the data is encrypted. Just the minimum of extensions are packed into the `data` field.
related: https://github.com/oasisprotocol/sapphire-paratime/pull/31

evm: expose public data in signed queries

---

cli/cmd/common/json.go
cli/cmd/contracts.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/contracts/types.go
client-sdk/ts-web/rt/src/contracts.ts
client-sdk/ts-web/rt/src/types.ts
runtime-sdk/modules/contracts/src/lib.rs
runtime-sdk/modules/contracts/src/store.rs
runtime-sdk/modules/contracts/src/test.rs
runtime-sdk/modules/contracts/src/types.rs
tests/contracts/hello/src/lib.rs

- Adds `contracts.InstanceRawStorage` to runtime API which returns a complete contract store for provided instance.
- Updates client-sdk/go bindings.
- Updates client-sdk/ts-web bindings
- Adds `oasis contracts storage get <instance-id> <key>` to Oasis CLI which calls `contracts.InstanceStorageQuery` and prints the value of given key in JSON stored in public contract store
- Adds `oasis contracts storage dump <instance-id> [--kind {public|confidential}] [--limit LIMIT] [--offset OFFSET]` to Oasis CLI which calls `contracts.InstanceRawStorageQuery` and prints the complete contract state in JSON
Example:
```
$ oasis contracts storage dump 0 --network localhost 
Showing 2 public record(s) of contract 0:
{"c2Vuc29yc1zFnd5u3TSZ":{"storage_granularity":600,"name":"esp2866_bedroom","measurement_t …
```

cli: Add contracts state dump support

---

docs/index.md

In light of the docs restructuring https://github.com/oasisprotocol/docs/pull/200 replace any `/oasis-core/*` or `/general/*` links with full github.com URL.
Redirection back to the documentation's URL should be done by docusaurus preprocessor.

docs: Replace /oasis-core links with full github URLs

---

client-sdk/go/testing/testing.go

This PR makes `oasis` CLI more tailored to local (dApp) development and debugging:
- adds `cory` test account which is the default entity created by `oasis-net-runner` when using `--fixture.default.fund_entities` flag

client-sdk/go: Add "cory" test key used by oasis-net-runner

---

Cargo.lock
runtime-sdk/Cargo.toml

Versions 1.21.0 and above do not build on x86_64-fortanix-unknown-sgx target.

Ensure tokio does not upgrade beyond 1.20.x

---

client-sdk/go/config/default.go
docs/contract/confidential-smart-contract.md

Replaces docs.oasis.dev references with docs.oasis.io.

docs: Migrate docs.oasis.dev -> docs.oasis.io

---

client-sdk/go/modules/evm/evm.go

match up with NewCallTx
context: we're making a simulation of the rust raw-eth-format tx decoding in go, so there's the desire to construct a evm.Create tx to represent the decoded tx without intending to send it over a runtime client

client-sdk/go: add evm NewCreateTx

---

runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs

This PR changes the confidential EVM create function to return the address, as would a non-confidential EVM. This will cause the gateway and downstream tools like the block explorer to display the correct address in the tx receipt.
There is no security risk to exposing the contract address, as it can be easily computed by observing that a transaction deposited new code (meaning a contract has been created) and then computing the address using the public sender address and nonce.
This PR should go in ASAP, as it's very annoying for devs who aren't able to use the block explorer as effectively.

evm: don't encode contract create output

---

client-sdk/ts-web/README.md
client-sdk/ts-web/core/README.md
client-sdk/ts-web/core/docs/getting-started.md

ts-web/core: docs additions

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/signer-ledger/package.json

a dependency that we use to communicate with the node, grpc-web, got rid of a method that we use. this happened in a minor version. let's release a version that's compatible so that things won't break if downstream projects update grpc-web.
fixes #1160

ts-web/core: v0.1.1-alpha.2

---

tools/gen_runtime_vectors/main.go
tools/gen_runtime_vectors/testvectors.go

This PR syncs test vectors with the new additions to [ADR14 PR](https://github.com/oasisprotocol/adrs/pull/6):
- adds Sapphire runtime ID for testnet
- removes `sig_context` from `Meta`
- adds invalid transaction with empty or too long `Meta.runtime_id` or `Meta.chain_context`.
- adds invalid transaction with unknown call format
- adds real-world ERC20 transfer call data input for `evm.Call` and for the encrypted transaction

gen_runtime_vectors: Sync with ADR14

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk/Cargo.toml
runtime-sdk/src/callformat.rs
tests/contracts/bench/Cargo.lock
tests/contracts/hello/Cargo.lock

This PR randomizes the nonce used to encrypt runtime responses when in simulate mode. This is useful for encrypted queries (as used by confidential EVM) which may see many queries being dispatched per block with corresponding loss of complete privacy. This could be fixed in client implementations, but you'd have to know to rekey your cipher before each call, which is not the most obvious thing to do.

runtime-sdk/callformat: randomize deoxysii nonce in simulation

---

runtime-sdk/src/runtime.rs

The previous behavior actually prevents queries from being performed against state before the runtime upgrade that included a global state migration.

runtime-sdk: Do not run global state migrations in queries

---

client-sdk/ts-web/core/src/client.ts

method descriptor .getName() will be fixed soon
https://github.com/grpc/grpc-web/commit/4974a7b5a98815113183f19298d9d9ffe93fbdad

ts-web/core: switch back to newly fixed getName

---

examples/contract-sdk/c10l-hello-world/Cargo.toml
examples/contract-sdk/hello-world/Cargo.toml

Followup to #1118 . Bumps examples/contract-sdk oasis-cbor dependency to avoid compilation errors.

examples/contract-sdk: Bump oasis-cbor to 0.5.0

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/playground/src/index.js
client-sdk/ts-web/core/src/client.ts

grpc-web can now handle falsy responses, such as getting signer nonce when the nonce is 0

ts-web/core: remove incomplete response workaround

---

docs/contract/confidential-smart-contract.md
docs/contract/hello-world.md

Minor additions to the Cipher chapters:
- Talks more about the Oasis confidential flow (related to https://github.com/oasisprotocol/docs/pull/310),
- describes the context object in relation to EVM in hello world chapter,
- describes call_format in the confidential hello world chapter.

docs: Add reference to the Context trait

---

client-sdk/go/client/client.go
client-sdk/go/types/event.go
client-sdk/go/types/event_test.go

Adds the related tx hash, if it exists, to runtime events returned by the runtime client.
Open questions: Do we need to support `evm` and `contracts` modules? Do those events have a related transaction? If yes, how do we want to update the `evm.Event` and `contracts.Event` without breaking the api? (Currently they are cbor-unmarshalled directly so updating the `Event` is not possible. Ideally we would wrap the event in a larger struct similar to the other modules, but this seems like a breaking change)
Edit**: We will leave the module level `Event`s unchanged.

[runtime-sdk] add txhash to Event

---

runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/test.rs

This PR changes confidential EVM to accept all calls instead of just enveloped ones. This makes it easier to accidentally send public transactions, but it makes it harder for third-party tooling to integrate. We could make the gateway more restrictive instead of the runtime. The gateway would see a mistakenly unencrypted tx anyway.

evm: allow unencrypted calls

---

runtime-sdk/modules/evm/src/precompile/confidential.rs
runtime-sdk/modules/evm/src/precompile/mod.rs

This PR adds a curve25519 public key generation precompile. This was added because it's not totally cool to use ed25519 keys for DH. Goes with https://github.com/oasisprotocol/sapphire-paratime/pull/116.

evm: add curve25519 public key generation precompile

---

client-sdk/go/client/client.go
client-sdk/go/crypto/signature/context.go
client-sdk/go/crypto/signature/context_test.go
client-sdk/go/crypto/signature/ed25519/signer.go
client-sdk/go/crypto/signature/secp256k1/secp256k1.go
client-sdk/go/crypto/signature/secp256k1/secp256k1_test.go
client-sdk/go/crypto/signature/secp256k1/signer.go
client-sdk/go/crypto/signature/signer.go
client-sdk/go/crypto/signature/sr25519/signer.go
client-sdk/go/helpers/address.go
client-sdk/go/helpers/address_test.go
client-sdk/go/types/transaction.go
client-sdk/go/types/transaction_test.go
tests/e2e/contracts.go
tests/e2e/simplekvtest.go
tests/e2e/txgen/txgen.go
tools/gen_runtime_vectors/README.md
tools/gen_runtime_vectors/main.go
tools/gen_runtime_vectors/testvectors.go

- Adds helpers for encoding the new `Meta` object used by Ledger for signing runtime transactions.
- BREAKING: Refactoring of `resolveAddress()` and `signature.Signer.ContextSign`

client-sdk: Add Context helpers for encoding Metadata used by hw wallets

---

client-sdk/go/callformat/callformat.go
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/src/callformat.rs
tests/e2e/evmtest.go

https://app.clickup.com/t/3c16qd5
https://app.clickup.com/t/863g4tpv3
Allow modules to customize the disclosure of failures in the pursuit of improved development environment.
_Note_. This is a backwards compatible change and the default is still encryption.

runtime-sdk: Allow custom modules to expose call result error

---

client-sdk/go/client/client.go
client-sdk/go/client/transaction.go
client-sdk/go/config/paratime.go
client-sdk/go/crypto/signature/context.go
client-sdk/go/helpers/denomination.go
client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/accounts/types.go
client-sdk/go/modules/consensus/consensus.go
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/consensusaccounts/types.go
client-sdk/go/modules/contracts/contracts.go
client-sdk/go/modules/core/core.go
client-sdk/go/modules/evm/evm.go
client-sdk/go/modules/rewards/rewards.go
client-sdk/go/types/address.go
client-sdk/go/types/token.go
client-sdk/go/types/token_test.go
client-sdk/go/types/transaction.go
client-sdk/go/types/transaction_test.go
tools/gen_runtime_vectors/testvectors.go

Required by oasisprotocol/cli#8.
- registers all known runtime methods using `NewMethodName` similar to oasis-core
- adds `PrettyTransaction` which actually knows how to print `Transaction` in a user-friendly way
- implements PrettyPrinter for runtime `Transaction`, `UnverifiedTransaction` and `Fee`
- implements PrettyPrinter for `BaseUnits`
- implements PrettyPrinter for token transfer transactions (Transfer, Deposit, Withdraw)
- adds unit tests

PrettyPrinter for runtime txes

---

client-sdk/ts-web/core/package.json
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/signer-ledger/package.json

Apparently https://github.com/oasisprotocol/oasis-sdk/pull/1099 was not enough for NPM to link back to the repo. It probably wants repo field too

client/ts-web: add repo links to packages

---

client-sdk/go/helpers/address.go
client-sdk/go/testing/testing.go
tools/gen_runtime_vectors/main.go

Fix ETH address handling for non-secp256k1 test accounts.
Fixes https://github.com/oasisprotocol/cli/issues/63

[BREAKING] client-sdk: Fix ETH address format for test accounts

---

.github/workflows/ci-test.yaml
client-sdk/ts-web/core/cypress.config.ts
client-sdk/ts-web/core/cypress/e2e/playground.cy.ts
client-sdk/ts-web/core/cypress/outputConsoleLogs.ts
client-sdk/ts-web/core/package.json
client-sdk/ts-web/ext-utils/cypress.config.ts
client-sdk/ts-web/ext-utils/cypress/e2e/playground.cy.ts
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/rt/cypress.config.ts
client-sdk/ts-web/rt/cypress/e2e/playground.cy.ts
client-sdk/ts-web/rt/package.json

Makes it easy to see how cypress playground tests are progressing
(partially extracted from https://github.com/oasisprotocol/oasis-sdk/pull/1246)

ts-web/*: Cypress forward console logs from browser to terminal

---

client-sdk/go/config/default.go

Sets `sapphire` as default ParaTime in go client-sdk. E.g. to be used by Oasis CLI when running it for the first time.

feat(go): Make sapphire default ParaTime

---

Cargo.lock
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/consensusaccounts/types.go
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk/Cargo.toml
runtime-sdk/src/context.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/history.rs
runtime-sdk/src/lib.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/consensus/mod.rs
runtime-sdk/src/modules/consensus_accounts/mod.rs
runtime-sdk/src/modules/consensus_accounts/state.rs
runtime-sdk/src/modules/consensus_accounts/test.rs
runtime-sdk/src/modules/consensus_accounts/types.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/rewards/mod.rs
runtime-sdk/src/modules/rewards/test.rs
runtime-sdk/src/storage/typed.rs
runtime-sdk/src/testing/mock.rs
tests/contracts/bench/Cargo.lock
tests/contracts/hello/Cargo.lock
tests/e2e/runtime.go
tests/e2e/scenarios.go
tests/e2e/simple_consensus.go
tests/runtimes/simple-consensus/src/lib.rs

runtime-sdk: Add support for consensus staking

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk/Cargo.toml
tests/contracts/hello/Cargo.lock

Upstream issue https://github.com/fortanix/rust-sgx/issues/497 was fixed so this is no longer needed.

runtime-sdk: Remove dcap-ql pin since it was fixed upstream

---

runtime-sdk/modules/evm/src/precompile/mod.rs

Commenting _bump evm to 0.39.1_ commit that was merged in #1420 .

runtime-sdk: Charge precompile extra cost

---

.github/workflows/ci-lint.yml
.github/workflows/ci-test.yaml

14 is eol, so we probably don't have to support it

ci: bump nodejs to 16

---

.cargo/audit.toml

This vulnerability does not affect our current use of the library.

cargo: Ignore RUSTSEC-2022-0093 until we can update ed25519-dalek to v2

---

runtime-sdk/src/dispatcher.rs

Note that in practice this is a no-op as Oasis Core will perform the rollback in any case. This just makes it explicit.

runtime-sdk: Always rollback any changes to storage from queries

---

runtime-sdk/modules/evm/src/backend.rs
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/state.rs
runtime-sdk/modules/evm/src/test.rs
runtime-sdk/modules/evm/src/types.rs

Given further thought this seems too much like a foot gun and may need some more thought.

runtime-sdk/modules/evm: Revert "drop signed queries in new contracts"

---

.github/workflows/ci-docs.yaml
.github/workflows/ci-test.yaml
client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/tsconfig.json
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/ext-utils/tsconfig.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/rt/tsconfig.json
client-sdk/ts-web/signer-ledger/package.json
client-sdk/ts-web/signer-ledger/tsconfig.json

This PR:
- adds or bumps typedoc of client-sdk/ts-web packages
- adds generation of typedoc to CI
- reorganizes api-reference branch to first include the language and inside the API reference of the corresponding packages (currently rust and js)
https://github.com/oasisprotocol/docs-api now also contains symbolic links merging together docs from oasis-sdk and sapphire-paratimes repos of different languages. Rust API reference links used at docs.oasis.io should now point to `https://api.docs.oasis.io/rust/*` instead of `https://api.docs.oasis.io/oasis-sdk`. Remove the `oasis-sdk` symbolic link in `api-reference` branch once the links on docs.oasis.io are updated.

api-reference: Add typedoc support, refactor

---

runtime-sdk/modules/evm/src/backend.rs
runtime-sdk/modules/evm/src/precompile/testing.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
tests/runtimes/benchmarking/src/lib.rs
tests/runtimes/simple-consensus/src/lib.rs
tests/runtimes/simple-contracts/src/lib.rs
tests/runtimes/simple-evm/src/lib.rs
tests/runtimes/simple-keyvalue/src/lib.rs
tests/runtimes/simple-keyvalue/src/test.rs

Adds support for dynamic min gas price inspired by EIP-1559

runtime-sdk: support dynamic min-gas-price

---

Cargo.lock
contract-sdk/crypto/Cargo.toml
contract-sdk/crypto/src/x25519.rs
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk/Cargo.toml
runtime-sdk/modules/evm/Cargo.toml
runtime-sdk/modules/evm/src/precompile/confidential.rs
runtime-sdk/modules/evm/src/precompile/sha512.rs
runtime-sdk/src/crypto/signature/digests.rs
runtime-sdk/src/crypto/signature/ed25519.rs
runtime-sdk/src/crypto/signature/mod.rs
runtime-sdk/src/crypto/signature/sr25519.rs
runtime-sdk/src/storage/confidential.rs
tests/contracts/hello/Cargo.lock

I had some trouble getting `p384` working because `sha2`, `ed25519_dalek`, and a few other crypto deps were a version behind. Such is the state of Rust crypto. Anyway, this PR does not change any functionality, but I did remove one test for rejecting all-zero ed25519 private keys because `[0u8; 32]` is a valid private key, just not one you'd want to use.

runtime-sdk: bump crypto deps

---

.github/workflows/ci-dependabot-fixup.yml
.github/workflows/ci-test.yaml
.gitignore
tools/gomod-updater/go.mod
tools/gomod-updater/go.sum
tools/gomod-updater/main.go

Makes dependabot useful for go projects in this repo:
- Adds tools/gomod-updater which supports updating the provided package in all go projects in the repo that use the package.
- Setups a Github workflow that runs on all dependabot PR's and updates the package in all projects.
See example: https://github.com/ptrus/oasis-sdk/pull/3

tools/gomod-updater: Fix Go Dependabot PR's automatically

---

.github/workflows/ci-dependabot-fixup.yml

Some followup fixes for: https://github.com/oasisprotocol/oasis-sdk/pull/1529
Tested in: https://github.com/ptrus/oasis-sdk/pull/22

ci-dependabot-fixup: fixes

---

tests/e2e/evmtest.go
tests/e2e/simple_consensus.go

This should fix the flakiness in testing the Undelegations query (example fail: https://github.com/oasisprotocol/oasis-sdk/actions/runs/6557914828/job/17810433096?pr=1488)

tests/simple-consensus: use exact rounds for testing undelegations

---

tests/benchmark/cmd/fixture.go

This fixes the benchmarks so that the run succeeds (the concurency is kept low, as the p2p settings cannot easily be configured via the fixture).

benchmarks: fix fixture by configuring runtime provisioner

---

runtime-sdk/src/crypto/signature/secp256k1.rs
runtime-sdk/src/crypto/signature/secp256r1.rs
runtime-sdk/src/crypto/signature/secp384r1.rs

This PR removes the requirement that public keys provided to the ECDSA precompiles be in compressed format. Sometimes all the user has is an uncompressed one and the curve is not gas-efficient in Solidity. The restriction seems to be for no particular reason, so I removed it because it significantly limits the utility of the precompiles.

runtime-sdk: remove compressed format requirement from ECDSA precompiles

---

client-sdk/ts-web/core/docs/changelog.md
client-sdk/ts-web/core/docs/getting-started.md
client-sdk/ts-web/core/package.json
client-sdk/ts-web/core/tsconfig.json
client-sdk/ts-web/ext-utils/docs/changelog.md
client-sdk/ts-web/ext-utils/package.json
client-sdk/ts-web/ext-utils/tsconfig.json
client-sdk/ts-web/package-lock.json
client-sdk/ts-web/rt/docs/changelog.md
client-sdk/ts-web/rt/package.json
client-sdk/ts-web/rt/tsconfig.json
client-sdk/ts-web/signer-ledger/docs/changelog.md
client-sdk/ts-web/signer-ledger/package.json
client-sdk/ts-web/signer-ledger/tsconfig.json

so downstream users can get rid of that nagging about protobufjs 7.1.x having a vulnerability

ts-web: 1.0 releases

---

examples/contract-sdk/c10l-hello-world/rust-toolchain.toml
examples/contract-sdk/hello-world/rust-toolchain.toml
examples/runtime-sdk/minimal-runtime/Cargo.toml
examples/runtime-sdk/minimal-runtime/rust-toolchain.toml

Unblocks https://github.com/oasisprotocol/oasis-sdk/pull/1600

deps: Bump rust toolchain for minimal-runtime to 2023-09-12

---

docs/contract/confidential-smart-contract.md
docs/contract/hello-world.md
docs/contract/prerequisites.md
docs/runtime/minimal-runtime.md
docs/runtime/prerequisites.md

Docusaurus 3.x markdown linter is more strict. This PR:
- fixes more strict linter errors
- refreshes docs/runtime/minimal-runtime.md looking more consistent with other parts of docs and updates the Oasis CLI commands

docs: Fix broken anchors

---

runtime-sdk/modules/contracts/src/abi/oasis/test.rs
runtime-sdk/src/dispatcher.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/state.rs
runtime-sdk/src/storage/mkvs.rs
runtime-sdk/src/storage/mod.rs
runtime-sdk/src/storage/overlay.rs
tests/runtimes/simple-keyvalue/src/lib.rs

Introduce the notion of storage gas which is charged for each byte of a key/value pair that is updated in storage. For removals only the size of the key is charged. The reason for this is to reflect actual costs that storage updates have (as any state update increases the size of the write log).
Storage gas is handled in a somewhat special way where any gas already used by transaction execution is taken into account. This means that storage gas is only charged in case a transaction would use more storage gas than execution gas in order to limit storage growth.

runtime-sdk: Support storage update gas costs

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk/Cargo.toml
runtime-sdk/modules/contracts/Cargo.toml
tests/contracts/hello/Cargo.lock

This PR:
- Bumps shlex to 1.3.0
- oasis-runtime-sdk-contracts: Bumps wasm3 to 0.3.2 (which bumps shlex to 1.3.0)

Bump wasm3-rs to 0.3.2

---

client-sdk/go/modules/accounts/accounts.go
client-sdk/go/modules/consensusaccounts/consensus_accounts.go
client-sdk/go/modules/contracts/types.go
client-sdk/go/modules/rewards/types.go
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/consensus_accounts/mod.rs
runtime-sdk/src/modules/rewards/mod.rs

This PR:
- Mentions the pool address in the comments similar to how we do it in [oasis-core](https://github.com/oasisprotocol/oasis-core/blob/master/go/staking/api/address_internal.go).
- Adds missing pending-withdrawal and pending-delegations addresses
Tag `runtime-sdk/v0.8.4` after merge.
Blocked by https://github.com/oasisprotocol/oasis-sdk/pull/1617
Required by https://github.com/oasisprotocol/cli/pull/134

client-sdk: Add pending-withdrawal and pending-delegation addresses

---

client-sdk/go/helpers/address.go
client-sdk/go/helpers/address_test.go
examples/runtime-sdk/minimal-runtime/Cargo.toml
tools/gen_runtime_vectors/main.go

This PR:
- Removes `ResolveAddress()` helper which was moved to Oasis CLI (https://github.com/oasisprotocol/cli/pull/134)
- Adds test for `ResolveEthOrOasisAddress()`
- deps: bumps minimal-runtime example runtime-sdk dependency to 0.8.4
Merge after https://github.com/oasisprotocol/cli/pull/134 and when the `runtime-sdk/v0.8.4` tag is pushed after https://github.com/oasisprotocol/oasis-sdk/pull/1507

client-sdk/go: Migrate ResolveAddress to Oasis CLI

---

client-sdk/go/config/default.go

Motivation: The config being expanded here is used by Nexus to know what human-readable configs mean by the string "pontusx".

client-sdk/config: Add Pontus-X chain

---

client-sdk/go/config/paratime.go

When parsing the config file the denomination ID may get transformed to lower case which will prevent the denomination from being resolved correctly.

client-sdk/go: Fix denomination resolution

---

client-sdk/ts-web/rt/playground/src/consensus.js
runtime-sdk/modules/evm/src/raw_tx.rs
runtime-sdk/src/modules/consensus/mod.rs
runtime-sdk/src/modules/core/mod.rs
runtime-sdk/src/modules/core/test.rs
runtime-sdk/src/state.rs
runtime-sdk/src/types/transaction.rs
tests/e2e/evmtest.go
tests/e2e/simple_consensus.go

Previously one had to explicitly configure the maximum number of messages to consensus layer that can be emitted by a transaction. This posed a problem for Ethereum-compatible transactions which don't support this field.
This implementation adds message emission gas which is dynamically calculated based on MAX_BATCH_GAS and MAX_MESSAGES. Similar to storage gas, it is only charged in case other use is too small in order to limit the total number of messages that can be emitted in a batch.
All Ethereum-compatible transactions now use this dynamic limit for the maximum number of consensus messages to be emitted.

runtime-sdk: Implement message emission gas

---

client-sdk/go/modules/core/core.go

Seems that V1 already integrated client.EventDecoder, the interface is just not complete. By adding client.EventDecoder we can pass it as a decoder in `func WatchEvents`
Without `client.EventDecoder` this will throw an error.
```go
decoders := []client.EventDecoder{
core.NewV1(runtimeClient),
}
eventsCh, err := runtimeClient.WatchEvents(ctx, decoders, true)
```
Error:
```
cannot use core.NewV1(runtimeClient) (value of type "github.com/oasisprotocol/oasis-sdk/client-sdk/go/modules/core".V1) as client.EventDecoder value in array or slice literal: "github.com/oasisprotocol/oasis-sdk/client-sdk/go/modules/core".V1 does not implement client.EventDecoder (missing method DecodeEvent)
```
With fix applied you can properly decode `Events` from `core` module, e.g.:
```json …
```

client-sdk/modules: Fix missing client.EventDecoder

---

.github/dependabot.yml

Create a rust group to update all rust dependencies in a single PR. This works nicely in oasis-core:  https://github.com/oasisprotocol/oasis-core/pull/5656
Also use the [multi-directory-beta-feature](https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/) to (hopefully) update all cargo projects within a single PR - this is the main issue currently preventing dependabot for rust to be useful in this repo, since updating dependency only in a single project causes dependent projects to fail CI. 
If this works nice, we should also enable it for go, instead of the hacky workaround currently used.

.github/dependabot: group all updates across all projects

---

client-sdk/go/config/default.go

What was previously called "pontusx" is now "pontusx-dev" and there is a new "pontusx-test", both on Testnet.

client-sdk/go/config: Refactor Pontus-X runtimes on Testnet

---

client-sdk/ts-web/core/src/address.ts
client-sdk/ts-web/core/src/common.ts
client-sdk/ts-web/core/src/consensus.ts
client-sdk/ts-web/core/src/genesis.ts
client-sdk/ts-web/core/src/hash.ts
client-sdk/ts-web/core/src/signature.ts
client-sdk/ts-web/core/src/staking.ts
client-sdk/ts-web/rt/playground/src/consensus.js
client-sdk/ts-web/rt/src/address.ts
client-sdk/ts-web/rt/src/callformat.ts
client-sdk/ts-web/rt/src/signature_secp256k1.ts
client-sdk/ts-web/rt/src/transaction.ts

The `hash.ts:hash` function is unnecessarily async, this has a knock-on effect making many simple functions also async where really they're deterministic.
This change means I can derive addresses in a `constructor`, such as:
```typescript
export class OasisSigner {
public readonly signer: oasis.signature.Signer;
public readonly address: Uint8Array;
public readonly addressBech32: string;
constructor(public readonly client: OasisClient, public readonly secret: Uint8Array) {
this.signer = oasis.signature.NaclSigner.fromSecret(secret, 'this key is not important');
this.address = oasis.staking.addressFromPublicKey(this.signer.public())
this.addressBech32 = oasis.staking.addressToBech32(this.address);
}
...
}
```
You can't have async code in constructors, so the alternative would be an async …

ts-web: removed unnecessary async from hash function

---

tools/orc/go.mod
tools/orc/go.sum

Having these present in go.mod prevents the tool from being directly installable.

tools/orc: Remove replace directives

---

Cargo.lock
runtime-sdk/src/modules/rofl/app/client.rs
runtime-sdk/src/modules/rofl/app/mod.rs
tests/runtimes/components-rofl/Cargo.toml
tests/runtimes/components-rofl/src/main.rs

The previous solution required the same SDK versions for ROFL and RONL which seems like an artificial constraint that could get annoying in practice. This should reduce developer friction.

runtime-sdk/modules/rofl: Reduce coupling between ROFL and RONL

---

.github/actions/hash-rust/action.yml
.github/actions/lint-rust/action.yml
.github/actions/test-rust/action.yml

Prevents theoretical `image: ghcr.io/oasisprotocol/runtime-builder:main; echo injected` in
https://github.com/oasisprotocol/oasis-sdk/blob/2057e22fac35f61159e6ae2871b99e047bb5f500/.github/workflows/ci-reproducibility.yml#L45-L48

Harden github workflow against injection

---

Cargo.lock
rofl-utils/Cargo.toml
rofl-utils/src/https.rs

This removes the need to maintain an ureq fork and brings in mbedtls support into the `rofl-utils` crate (also see discussion in https://github.com/algesten/ureq/pull/791). There is some code duplication with `ureq` TLS, but on the other hand we have our own connectors/transports for SGX anyway.

rofl-utils: Get rid of ureq fork, bring mbedtls support locally

---

client-sdk/go/modules/rofl/rofl.go
client-sdk/go/modules/rofl/types.go
runtime-sdk/src/modules/rofl/config.rs
runtime-sdk/src/modules/rofl/error.rs
runtime-sdk/src/modules/rofl/mod.rs
runtime-sdk/src/modules/rofl/types.rs
tests/e2e/rofl/tests.go
tests/runtimes/components-ronl/src/oracle/mod.rs

Closes #1924 
This makes it possible to query the endorsing node and entity of the origin ROFL app instance.

runtime-sdk/modules/rofl: Add rofl.AuthorizedOrigin{Node,Entity}

---

.github/actions/hash-rust/action.yml

Straight forward implementation of #1947. Passing empty features, e.g. `--features ""` works perfectly fine.

.github/actions/hash-rust: Add features parameter

---

.github/actions/test-rust/action.yml

This one seems to have been left out when upgrading the `upload-artifact` versions (https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).

CI: Bump upload-artifact action version to v4 in test-rust

---

docs/rofl/deployment.md
examples/runtime-sdk/rofl-oracle/policy.yml
examples/runtime-sdk/rofl-oracle/policy2.yml

The enclaves and endorsements fields were mixed up. This PR properly fixes those.

docs: Fix ROFL policy file

---

docs/rofl/prerequisites.md

`oasis rofl build sgx --mode unsafe` fails following current instructions on plain ubuntu during the SGXS compilation. You need to install `gcc-multilib`.

docs: Add gcc-multilib dependency in order to compile rofl

---

docs/README.md

Update the link from https://github.com/oasisprotocol/oasis-core/blob/master/docs/runtime/index.md to https://github.com/oasisprotocol/oasis-core/blob/master/docs/runtime/README.md

feat(docs):update link

---

client-sdk/go/config/network.go
client-sdk/go/connection/connection.go

This usecase came up in https://github.com/oasisprotocol/oasis-web3-gateway/pull/626 since we want to expose the node from docker via a port (since this works better cross-platform than exposing the socket via a volume).
The alternative possible solution would be to provide a flag that allows insecure connections or connections with self-signed certs (something like --insecure in curl).
BTW we might want to do the same in oasis-core: https://github.com/oasisprotocol/oasis-core/blob/280d2ef1947bc9baaeb390c3131a08b87824c9ef/go/oasis-node/cmd/common/grpc/grpc.go#L83-L89
since ideally, both `oasis-node` and `oasis-cli` would work with local-net without much hassle.
cc @matevz 
TODO:

client-sdk: allow insecure connections to localhost address

---

docs/rofl/app.md
docs/rofl/deployment.md

Necessary for https://github.com/oasisprotocol/docs/issues/959. Blocked by https://github.com/oasisprotocol/docs/pull/977

docs: Sapphire localnet references consolidated page under tools

---

client-sdk/go/modules/rofl/rofl.go
client-sdk/go/modules/rofl/types.go
runtime-sdk/src/modules/rofl/config.rs
runtime-sdk/src/modules/rofl/mod.rs
runtime-sdk/src/modules/rofl/types.rs
tests/e2e/rofl/tests.go
tests/runtimes/components-ronl/src/lib.rs

This PR adds `rofl.StakeThresholds` query to runtime-sdk and client-sdk/go.
Fixes #1993

runtime-sdk: Add rofl.StakeThresholds query

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
examples/runtime-sdk/rofl-oracle/Cargo.lock
runtime-sdk/modules/evm/Cargo.toml
runtime-sdk/modules/evm/src/precompile/confidential.rs
runtime-sdk/src/crypto/signature/ed25519.rs
runtime-sdk/src/crypto/signature/mod.rs
runtime-sdk/src/crypto/signature/secp256k1.rs
runtime-sdk/src/crypto/signature/secp256r1.rs
runtime-sdk/src/crypto/signature/secp384r1.rs
runtime-sdk/src/crypto/signature/sr25519.rs
tests/contracts/bench/Cargo.lock
tests/contracts/hello/Cargo.lock

runtime-sdk: Add sr25519 support in EVM precompiles

---

client-sdk/go/modules/rofl/types.go

This PR implements `PrettyPrint()` for `StakeThresholds`. Improves output of https://github.com/oasisprotocol/cli/pull/318 to
```
$ oasis paratime show parameters --network testnet
Network:        testnet
ParaTime:       sapphire
=== ROFL PARAMETERS ===
Stake thresholds:
App create: 10000.0 TEST
```

client-sdk: Add PrettyPrint to StakeThresholds

---

client-sdk/go/client/client.go

Set transaction hash for events in `GetTransactionsWithResults`.

client-sdk/go: GetTransactionWithResults include txhash in events

---

docs/rofl/app.md
docs/rofl/prerequisites.md

Tweak docs to address potential `No ROFLs detected` while running localstack:
- Make sure sapphire-localnet container is not outdated 
- Commands where not clear or accurate (at least for me)
- Adjust ports so users can access local Nexus and Explorer

Update ROFL app docs

---

docs/rofl/deployment.md

Needed for https://github.com/oasisprotocol/docs/pull/1041

fix: link to cipher docs

---

docs/rofl/app.mdx
docs/rofl/deployment.md

- changes dapp path to build
needed for https://github.com/oasisprotocol/docs/pull/1058

docs: dapp to build refactor

---

Cargo.lock
rofl-containers/Cargo.toml
runtime-sdk/src/modules/rofl/app/mod.rs
runtime-sdk/src/modules/rofl/app/processor.rs
runtime-sdk/src/modules/rofl/app/registration.rs
runtime-sdk/src/modules/rofl/app/watchdog.rs

Fixes #2143 
The watchdog task ensures that the app is successfully re-registering and terminates it if this is not the case.

runtime-sdk/modules/rofl: Add watchdog task

---

client-sdk/go/modules/rofl/rofl.go
client-sdk/go/modules/rofl/types.go
runtime-sdk/src/modules/rofl/event.rs
runtime-sdk/src/modules/rofl/mod.rs
runtime-sdk/src/modules/rofl/state.rs
runtime-sdk/src/modules/rofl/test.rs
tests/e2e/rofl/tests.go

Fixes: https://github.com/oasisprotocol/oasis-sdk/issues/2158 https://github.com/oasisprotocol/oasis-sdk/issues/2157

rofl: Add Apps query and emit event on instance registration

---

tools/orc/main.go

tools/orc: Add support for ephemeral signer key

---

docs/rofl/app.mdx

docs: Add warning to use FQDN URLs for docker images

---

Cargo.lock
contract-sdk/specs/access/oas173/Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
docs/rofl/app.mdx
examples/runtime-sdk/rofl-oracle-tdx/Cargo.lock
examples/runtime-sdk/rofl-oracle/Cargo.lock
tests/contracts/bench/Cargo.lock
tests/contracts/hello/Cargo.lock

Should be merged shortly after a new CLI release which includes https://github.com/oasisprotocol/cli/pull/391.

docs/rofl: Update for new version of Oasis CLI

---

docs/rofl/features.md

New line should not be captured inside the env variable.

docs: Fix echo command for storing secrets

---

Cargo.lock
contract-sdk/specs/token/oas20/Cargo.lock
runtime-sdk-macros/Cargo.toml
runtime-sdk-macros/src/evm_derive.rs
runtime-sdk-macros/src/lib.rs
runtime-sdk/modules/evm/Cargo.toml
runtime-sdk/modules/evm/fuzz/README.md
runtime-sdk/modules/evm/fuzz/precompile_contract_dispatch.rs
runtime-sdk/modules/evm/fuzz/precompile_contract_dispatch_corpus.rs
runtime-sdk/modules/evm/fuzz/precompile_corpus.rs
runtime-sdk/modules/evm/src/lib.rs
runtime-sdk/modules/evm/src/precompile/contract.rs
runtime-sdk/modules/evm/src/precompile/erc20.rs
runtime-sdk/modules/evm/src/precompile/mod.rs
runtime-sdk/modules/evm/src/test.rs
runtime-sdk/src/modules/accounts/mod.rs
runtime-sdk/src/modules/accounts/test.rs
tests/contracts/hello/Cargo.lock

runtime-sdk: Implement ERC-20 compatibility

---

docs/rofl/quickstart.mdx

for MAC users - we get this error  when running
TOKEN=$TOKEN python bot.py 
the fix is changing the square brackets to ()
Traceback (most recent call last):
File "/Users/jordan/Desktop/testing/demo/bot.py", line 10, in <module>
app = ApplicationBuilder().token(os.getenv["TOKEN"]).build()
TypeError: 'function' object is not subscriptable

docs: rofl/quickstart - changed brackets from [] to ()

---

runtime-sdk/modules/rofl-market/src/lib.rs

In these two places, the instance was updated, but no `InstanceUpdated` event was emitted.

runtime-sdk/roflmarket: Add missing instance update events

---

client-sdk/go/modules/core/core.go
tests/e2e/evm/eth_tx.go
tests/e2e/evm/tests.go

The Go client method `MinGasPrice` did not accept a round parameter and always queried the latest round.
Querying `MinGasPrice` for past rounds is necessary to calculate the charged fee for EVM EIP-1559 transactions, where the effective gas price depends on the base fee at the round of transaction (which corresponds to the min gas price in our case).

go/client-sdk/core: Add round parameter to MinGasPrice

---

docker/rofl-dev/Dockerfile

Upgrading CLI to `14.0` and Core to `25.4.x` for `rofl-dev` Docker image.

docker/rofl-dev: Bump CLI to 14.0 and Core to 25.4.x

---

client-sdk/ts-web/core/src/quantity.ts

the library is still very much "only help when you already know what you're doing" but look at this badness
```ts
import * as oasis from '@oasisprotocol/client';
console.log(oasis.quantity.toBigInt(oasis.quantity.fromBigInt(-10n)));
// 246n
```

ts-web/core: throw on quantity from negative bigint

---

Cargo.lock
rofl-app-core/Cargo.toml
rofl-app-core/src/registration.rs

rofl-app-core: Retry registration using exponential backoff

---

docs/rofl/features/rest.md

Fixes https://github.com/oasisprotocol/oasis-sdk/issues/2280
Now contains a real-world CBOR-encoded message in the example response.

docs/rofl: Fix sign-submit response

---

.github/workflows/release-rofl-client-py.yml
rofl-client/py/CHANGELOG.md

There were some missing workdirs in the publish workflow.

rofl-client-py: Prepare release 0.1.1

---

.github/workflows/release-rofl-client-py.yml
rofl-client/py/CHANGELOG.md
rofl-client/py/pyproject.toml

- fixed namespace stripping for correct version in workflow and hatch versioning

rofl-client-py: Perpare 0.1.3 release

---

rofl-client/py/CHANGELOG.md
rofl-client/py/README.md
rofl-client/py/pyproject.toml

- fix root for hatch, that hatch can see git tags
(was before not seeing tags and falling back to 0.0.0)
(works now correctly on my [fork](https://github.com/rube-de/oasis-sdk/actions/runs/18011169927))

rofl-client-py: Prepare 0.1.4 release
